"""delete_detach_unit

Revision ID: 07968b6c8b4d
Revises: ec86423f1838
Create Date: 2025-11-26 14:04:05.111031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07968b6c8b4d'
down_revision = 'ec86423f1838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collision', schema='TAR') as batch_op:
        batch_op.drop_column('detachment_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collision', schema='TAR') as batch_op:
        batch_op.add_column(sa.Column('detachment_unit', sa.VARCHAR(length=30), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
