"""add_entity_type_position_safety_3

Revision ID: 0b9e4209b498
Revises: 1a1b4b10a068
Create Date: 2025-11-20 15:55:14.034218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9e4209b498'
down_revision = '1a1b4b10a068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('involved_person', schema='TAR') as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.String(length=1), nullable=True))

    op.execute('''
        Update "TAR"."involved_person" ip
        Set entity_type = e.entity_type
        From "TAR"."entity" e
        Where ip.entity_id = e.entity_id;
    ''')

    with op.batch_alter_table('involved_person', schema='TAR') as batch_op:
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
        batch_op.create_foreign_key('involved_person_safety_equipment_used_entity_type_fkey', 'safety_equipment', ['entity_type', 'safety_equipment_used'], ['entity_type', 'code'], referent_schema='TAR')
        batch_op.create_foreign_key('involved_person_entity_type_fkey', 'entity_type', ['entity_type'], ['code'], referent_schema='TAR')
        batch_op.create_foreign_key('involved_person_position_of_person_entity_type_fkey', 'position', ['entity_type', 'position_of_person'], ['entity_type', 'code'], referent_schema='TAR')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('involved_person', schema='TAR') as batch_op:
        batch_op.drop_constraint('involved_person_position_of_person_entity_type_fkey', type_='foreignkey')
        batch_op.drop_constraint('involved_person_safety_equipment_used_entity_type_fkey', type_='foreignkey')
        batch_op.drop_constraint('involved_person_entity_type_fkey', type_='foreignkey')
        batch_op.drop_column('entity_type')

    # ### end Alembic commands ###
