"""empty message

Revision ID: 0cd359646c78
Revises: 0f251cbbfb53
Create Date: 2023-10-11 17:39:45.960218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd359646c78'
down_revision = '0f251cbbfb53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impound_lot_operator', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'impound_lot_operator', ['impound_lot_operator'], ['id'])
        batch_op.drop_column('printed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('printed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('submitted')
        batch_op.drop_column('impound_lot_operator')

    # ### end Alembic commands ###
