"""empty message

Revision ID: 0f251cbbfb53
Revises: 43b7e19ba2e4
Create Date: 2023-10-11 16:49:56.685322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f251cbbfb53'
down_revision = '43b7e19ba2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intersection_or_address_of_offence', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('offence_city', sa.String(), nullable=True))
        batch_op.alter_column('regist_owner_phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('twenty_four_hour_form', schema=None) as batch_op:
        batch_op.drop_column('offence_city')
        batch_op.drop_column('intersection_or_address_of_offence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twenty_four_hour_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intersection_or_address_of_offence', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('offence_city', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('regist_owner_phone',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('offence_city')
        batch_op.drop_column('intersection_or_address_of_offence')

    # ### end Alembic commands ###
