"""empty message

Revision ID: 124b834870fb
Revises: 88651b385c11
Create Date: 2023-10-18 15:43:47.615975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124b834870fb'
down_revision = '88651b385c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vi_form', schema=None) as batch_op:
        batch_op.alter_column('irp_impound',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vi_form', schema=None) as batch_op:
        batch_op.alter_column('irp_impound',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
