"""empty message

Revision ID: 15ff36b63f1c
Revises: c021e4dd831c
Create Date: 2023-09-26 15:48:18.112782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ff36b63f1c'
down_revision = 'c021e4dd831c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_storage_refs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryptiv', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_storage_refs', schema=None) as batch_op:
        batch_op.drop_column('encryptiv')

    # ### end Alembic commands ###
