"""add_entity_type_position_safety

Revision ID: 1819b1381fcd
Revises: b9e6310b04b9
Create Date: 2025-11-20 12:15:27.074813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1819b1381fcd'
down_revision = 'b9e6310b04b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema='TAR') as batch_op:
        batch_op.alter_column('damage_location_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('severety_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)

    with op.batch_alter_table('position', schema='TAR') as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.String(length=1), nullable=True))
        batch_op.create_foreign_key('position_entity_type_fkey', 'entity_type', ['entity_type'], ['code'], referent_schema='TAR')

    with op.batch_alter_table('safety_equipment', schema='TAR') as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.String(length=1), nullable=True))
        batch_op.create_foreign_key('safety_equipment_entity_type_fkey', 'entity_type', ['entity_type'], ['code'], referent_schema='TAR')

    op.execute('''
        UPDATE "TAR"."position" SET entity_type = 'V';
    ''')
    op.execute('''
        UPDATE "TAR"."safety_equipment" SET entity_type = 'V';
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safety_equipment', schema='TAR') as batch_op:
        batch_op.drop_constraint('safety_equipment_entity_type_fkey', type_='foreignkey')
        batch_op.drop_column('entity_type')

    with op.batch_alter_table('position', schema='TAR') as batch_op:
        batch_op.drop_constraint('position_entity_type_fkey', type_='foreignkey')
        batch_op.drop_column('entity_type')

    with op.batch_alter_table('entity', schema='TAR') as batch_op:
        batch_op.alter_column('severety_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('damage_location_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)

    # ### end Alembic commands ###
