"""empty message

Revision ID: 1920269671bc
Revises: 2b0bb8892bc7
Create Date: 2023-10-26 17:36:31.011828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1920269671bc'
down_revision = '2b0bb8892bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regist_owner_email', sa.String(), nullable=True))

    with op.batch_alter_table('vi_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_is_regist_owner', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('out_of_province_dl_expiry', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vi_form', schema=None) as batch_op:
        batch_op.drop_column('out_of_province_dl_expiry')
        batch_op.drop_column('driver_is_regist_owner')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('regist_owner_email')

    # ### end Alembic commands ###
