"""remove_df_error_constraints

Revision ID: 1940b9b5da98
Revises: 691dbc1c9a0b
Create Date: 2026-05-21 14:21:38.243485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1940b9b5da98'
down_revision = '691dbc1c9a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('df_errors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('df_errors_event_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('df_errors_submission_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('df_errors', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('df_errors_submission_id_fkey'), 'submission', ['submission_id'], ['submission_id'])
        batch_op.create_foreign_key(batch_op.f('df_errors_event_id_fkey'), 'event', ['event_id'], ['event_id'])

    # ### end Alembic commands ###
