"""add_entity_type_position_safety_2

Revision ID: 1a1b4b10a068
Revises: 1819b1381fcd
Create Date: 2025-11-20 14:33:03.427016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1b4b10a068'
down_revision = '1819b1381fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('involved_person_position_of_person_fkey', 'involved_person', schema='TAR', type_='foreignkey')
    op.drop_constraint('involved_person_safety_equipment_used_fkey', 'involved_person', schema='TAR', type_='foreignkey')
    with op.batch_alter_table('position', schema='TAR') as batch_op:
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
        batch_op.drop_constraint('position_pkey', type_='primary')
        batch_op.create_primary_key('position_pkey', ['code', 'entity_type'])

    with op.batch_alter_table('safety_equipment', schema='TAR') as batch_op:
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
        batch_op.drop_constraint('safety_equipment_pkey', type_='primary')
        batch_op.create_primary_key('safety_equipment_pkey', ['code', 'entity_type'])


    op.execute('''
        Insert into "TAR"."position" (code, description, entity_type)
        Select '00', 'UNKNOWN', 'C'
        Where Not Exists (
            Select 1
            From "TAR"."position"
            Where code = '00' AND entity_type = 'C');
                              
        Insert into "TAR"."position" (code, description, entity_type)
        Select '01', 'DRIVER', 'C'
        Where Not Exists (
            Select 1
            From "TAR"."position"
            Where code = '01' AND entity_type = 'C');
               
        Insert into "TAR"."position" (code, description, entity_type)
        Select '04', 'PASSENGER', 'C'
        Where Not Exists (
            Select 1
            From "TAR"."position"
            Where code = '04' AND entity_type = 'C');
               
        Insert into "TAR"."position" (code, description, entity_type)
        Select '08', 'HANGER ON', 'C'
        Where Not Exists (
            Select 1
            From "TAR"."position"
            Where code = '08' AND entity_type = 'C');
               
        Insert into "TAR"."position" (code, description, entity_type)
        Select '99', 'OTHER', 'C'
        Where Not Exists (
            Select 1
            From "TAR"."position"
            Where code = '99' AND entity_type = 'C');
               
        Insert into "TAR"."position" (code, description, entity_type)
        Select '98', 'NOT APPLICABLE', 'P'
        Where Not Exists (
            Select 1
            From "TAR"."position"
            Where code = '98' AND entity_type = 'P');

        Insert into "TAR"."position" (code, description, entity_type)
        Select '01', 'DRIVER', 'O'
        Where Not Exists (
            Select 1
            From "TAR"."position"
            Where code = '01' AND entity_type = 'O');

        Insert into "TAR"."position" (code, description, entity_type)
        Select '98', 'NOT APPLICABLE', 'O'
        Where Not Exists (
            Select 1
            From "TAR"."position"
            Where code = '98' AND entity_type = 'O');
               
        Insert into "TAR"."position" (code, description, entity_type)
        Select '99', 'OTHER', 'O'
        Where Not Exists (
            Select 1
            From "TAR"."position"
            Where code = '99' AND entity_type = 'O');
    ''')

    # 08 – Helmet 09 – No Helmet 00 – Unknown 99 – Other
    op.execute('''
        Insert into "TAR"."safety_equipment" (code, description, entity_type)
        Select '00', 'UNKNOWN', 'C'
        Where Not Exists (
            Select 1
            From "TAR"."safety_equipment"
            Where code = '00' AND entity_type = 'C');
               
        Insert into "TAR"."safety_equipment" (code, description, entity_type)
        Select '08', 'HELMET', 'C'
        Where Not Exists (
            Select 1
            From "TAR"."safety_equipment"
            Where code = '08' AND entity_type = 'C');
               
        Insert into "TAR"."safety_equipment" (code, description, entity_type)
        Select '09', 'NO HELMET', 'C'
        Where Not Exists (
            Select 1
            From "TAR"."safety_equipment"
            Where code = '09' AND entity_type = 'C');
               
        Insert into "TAR"."safety_equipment" (code, description, entity_type)
        Select '99', 'OTHER', 'C'
        Where Not Exists (
            Select 1
            From "TAR"."safety_equipment"
            Where code = '99' AND entity_type = 'C');
               

        Insert into "TAR"."safety_equipment" (code, description, entity_type)
        Select '98', 'NOT APPLICABLE', 'P'
        Where Not Exists (
            Select 1
            From "TAR"."safety_equipment"
            Where code = '98' AND entity_type = 'P');
               
        Insert into "TAR"."safety_equipment" (code, description, entity_type)
        Select '98', 'NOT APPLICABLE', 'O'
        Where Not Exists (
            Select 1
            From "TAR"."safety_equipment"
            Where code = '98' AND entity_type = 'O');
        ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        Delete From "TAR"."position"
        Where code in ('00', '01', '04', '08', '99', '98')
          And entity_type in ('C', 'P', 'O');
    ''')
    op.execute('''
        Delete From "TAR"."safety_equipment"
        Where code in ('00', '08', '09', '99', '98')
          And entity_type in ('C', 'P', 'O');
    ''')

    with op.batch_alter_table('safety_equipment', schema='TAR') as batch_op:
        batch_op.drop_constraint('safety_equipment_pkey', type_='primary')
        batch_op.create_primary_key('safety_equipment_pkey', ['code'])
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)

    with op.batch_alter_table('position', schema='TAR') as batch_op:
        batch_op.drop_constraint('position_pkey', type_='primary')
        batch_op.create_primary_key('position_pkey', ['code'])
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)

    with op.batch_alter_table('involved_person', schema='TAR') as batch_op:
        batch_op.create_foreign_key('involved_person_position_of_person_fkey', 'position', ['position_of_person'], ['code'], referent_schema='TAR')
        batch_op.create_foreign_key('involved_person_safety_equipment_used_fkey', 'safety_equipment', ['safety_equipment_used'], ['code'], referent_schema='TAR')

    # ### end Alembic commands ###
