"""lki_tables

Revision ID: 1d9b5876488f
Revises: c15ff5018553
Create Date: 2025-09-26 11:42:13.182333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9b5876488f'
down_revision = 'c15ff5018553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lki_highway',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('lki_segment',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('hwy_code', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=1), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hwy_code'], ['TAR.lki_highway.code'], ),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.execute("""
        GRANT SELECT, UPDATE, DELETE, INSERT, REFERENCES ON TABLE "TAR".lki_highway TO df_db_app_user;
        GRANT SELECT, UPDATE, DELETE, INSERT, REFERENCES ON TABLE "TAR".lki_segment TO df_db_app_user;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lki_segment', schema='TAR')
    op.drop_table('lki_highway', schema='TAR')
    # ### end Alembic commands ###
