"""empty message

Revision ID: 1dff388c19fd
Revises: 4bb5f9bd304a
Create Date: 2023-09-13 12:36:13.551606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dff388c19fd'
down_revision = '4bb5f9bd304a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vi_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('driver_licence_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('driver_licence_class', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('unlicenced_prohibition_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('belief_driver_bc_resident', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('out_of_province_dl', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('out_of_province_dl_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date_of_impound', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('irp_impound', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('irp_impound_duration', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('IRP_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('VI_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('excessive_speed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('prohibited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('suspended', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('street_racing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stunt_driving', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('motorcycle_seating', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('motorcycle_restrictions', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('unlicensed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('linkage_location_of_keys', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('linkage_location_of_keys_explanation', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('linkage_driver_principal', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('linkage_owner_in_vehicle', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('linkage_owner_aware_possesion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('linkage_vehicle_transfer_notice', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('linkage_other', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('speed_limit', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_speed', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('speed_estimation_technique', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('speed_confirmation_technique', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('incident_details', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('incident_details_extra_page', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vi_form', schema=None) as batch_op:
        batch_op.drop_column('incident_details_extra_page')
        batch_op.drop_column('incident_details')
        batch_op.drop_column('speed_confirmation_technique')
        batch_op.drop_column('speed_estimation_technique')
        batch_op.drop_column('vehicle_speed')
        batch_op.drop_column('speed_limit')
        batch_op.drop_column('linkage_other')
        batch_op.drop_column('linkage_vehicle_transfer_notice')
        batch_op.drop_column('linkage_owner_aware_possesion')
        batch_op.drop_column('linkage_owner_in_vehicle')
        batch_op.drop_column('linkage_driver_principal')
        batch_op.drop_column('linkage_location_of_keys_explanation')
        batch_op.drop_column('linkage_location_of_keys')
        batch_op.drop_column('unlicensed')
        batch_op.drop_column('motorcycle_restrictions')
        batch_op.drop_column('motorcycle_seating')
        batch_op.drop_column('stunt_driving')
        batch_op.drop_column('street_racing')
        batch_op.drop_column('suspended')
        batch_op.drop_column('prohibited')
        batch_op.drop_column('excessive_speed')
        batch_op.drop_column('VI_number')
        batch_op.drop_column('IRP_number')
        batch_op.drop_column('irp_impound_duration')
        batch_op.drop_column('irp_impound')
        batch_op.drop_column('date_of_impound')
        batch_op.drop_column('out_of_province_dl_number')
        batch_op.drop_column('out_of_province_dl')
        batch_op.drop_column('belief_driver_bc_resident')
        batch_op.drop_column('unlicenced_prohibition_number')
        batch_op.drop_column('driver_licence_class')
        batch_op.drop_column('driver_licence_expiry')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
