"""empty message

Revision ID: 237614f969cf
Revises: b4b054d65515
Create Date: 2023-12-02 14:47:40.537260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237614f969cf'
down_revision = 'b4b054d65515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ilo_cross_ref',
    sa.Column('ilo_name', sa.String(), nullable=False),
    sa.Column('vips_impound_lot_operator_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ilo_name')
    )
    
    # Seed xref data
    with op.get_context().autocommit_block():
        bind = op.get_bind()
        meta = sa.MetaData()
        meta.bind = bind
        meta.reflect(bind=bind, only=('ilo_cross_ref',))
        ilo_cross_ref = sa.Table('ilo_cross_ref', meta)
        op.execute("DELETE FROM ilo_cross_ref")
        op.bulk_insert(ilo_cross_ref,
            [
                {
                    "ilo_name": "5 STAR TOWING",
                    "vips_impound_lot_operator_id": 153
                },
                {
                    "ilo_name": "A & M TOWING",
                    "vips_impound_lot_operator_id": 253
                },
                {
                    "ilo_name": "A J TOWING",
                    "vips_impound_lot_operator_id": 324
                },
                {
                    "ilo_name": "ABLE TOWING",
                    "vips_impound_lot_operator_id": 323
                },
                {
                    "ilo_name": "AGGRESSIVE AUTO TOWING",
                    "vips_impound_lot_operator_id": 127
                },
                {
                    "ilo_name": "ALBERNI TOWING",
                    "vips_impound_lot_operator_id": 188
                },
                {
                    "ilo_name": "ALL COAST TOWING SERVICES",
                    "vips_impound_lot_operator_id": 147
                },
                {
                    "ilo_name": "ALL-WAYS TOWING",
                    "vips_impound_lot_operator_id": 347
                },
                {
                    "ilo_name": "ANTLE TOWING",
                    "vips_impound_lot_operator_id": 360
                },
                {
                    "ilo_name": "APPLEWOOD TOWING",
                    "vips_impound_lot_operator_id": 308
                },
                {
                    "ilo_name": "ARROWSMITH TOWING",
                    "vips_impound_lot_operator_id": 49
                },
                {
                    "ilo_name": "AURORA TOWING",
                    "vips_impound_lot_operator_id": 837
                },
                {
                    "ilo_name": "AUTOW / QUESNEL TOWING",
                    "vips_impound_lot_operator_id": 311
                },
                {
                    "ilo_name": "BAILLIE'S TOWING",
                    "vips_impound_lot_operator_id": 356
                },
                {
                    "ilo_name": "BARRIERE AUTO & TRUCK TOW",
                    "vips_impound_lot_operator_id": 677
                },
                {
                    "ilo_name": "BAYVIEW AUTO TOWING",
                    "vips_impound_lot_operator_id": 332
                },
                {
                    "ilo_name": "BEE JAY TOWING",
                    "vips_impound_lot_operator_id": 254
                },
                {
                    "ilo_name": "BEN'S TOWING",
                    "vips_impound_lot_operator_id": 18
                },
                {
                    "ilo_name": "BKV TOWING",
                    "vips_impound_lot_operator_id": 13
                },
                {
                    "ilo_name": "BLACK BEAR TOWING",
                    "vips_impound_lot_operator_id": 274
                },
                {
                    "ilo_name": "BOYCE AUTO TOWING",
                    "vips_impound_lot_operator_id": 21
                },
                {
                    "ilo_name": "BRIDGE LAKE TOWING",
                    "vips_impound_lot_operator_id": 184
                },
                {
                    "ilo_name": "BUSTER'S TOWING",
                    "vips_impound_lot_operator_id": 23
                },
                {
                    "ilo_name": "CARIBOO TOWING",
                    "vips_impound_lot_operator_id": 155
                },
                {
                    "ilo_name": "CARIBOU SERVICE",
                    "vips_impound_lot_operator_id": 152
                },
                {
                    "ilo_name": "CENTRAL TOWING",
                    "vips_impound_lot_operator_id": 25
                },
                {
                    "ilo_name": "CHANOR TRUCK & AUTO REPAIR",
                    "vips_impound_lot_operator_id": 207
                },
                {
                    "ilo_name": "CHARLOTTE TIRE",
                    "vips_impound_lot_operator_id": 290
                },
                {
                    "ilo_name": "CHRISTINA LAKE TOWING",
                    "vips_impound_lot_operator_id": 28
                },
                {
                    "ilo_name": "CITY MOTORS",
                    "vips_impound_lot_operator_id": 27
                },
                {
                    "ilo_name": "CITY OF NEW WESTMINSTER TOWING",
                    "vips_impound_lot_operator_id": 229
                },
                {
                    "ilo_name": "CLASSIC TOWING (GOLDEN)",
                    "vips_impound_lot_operator_id": 272
                },
                {
                    "ilo_name": "CLASSIC TOWING (REVELSTOKE)",
                    "vips_impound_lot_operator_id": 107
                },
                {
                    "ilo_name": "CLEARWATER TOWING",
                    "vips_impound_lot_operator_id": 350
                },
                {
                    "ilo_name": "CLOVER TOWING",
                    "vips_impound_lot_operator_id": 389
                },
                {
                    "ilo_name": "CLUB TOWING & HEAVY RECOVERY",
                    "vips_impound_lot_operator_id": 977
                },
                {
                    "ilo_name": "COASTLINE TOWING",
                    "vips_impound_lot_operator_id": 30
                },
                {
                    "ilo_name": "COLLISION CRAFT / USHER'S TOWING",
                    "vips_impound_lot_operator_id": 394
                },
                {
                    "ilo_name": "COMOX VALLEY DODGE",
                    "vips_impound_lot_operator_id": 388
                },
                {
                    "ilo_name": "COOPER'S TOWING",
                    "vips_impound_lot_operator_id": 1017
                },
                {
                    "ilo_name": "COQUITLAM TOWING",
                    "vips_impound_lot_operator_id": 32
                },
                {
                    "ilo_name": "DAKOTA TOWING",
                    "vips_impound_lot_operator_id": 917
                },
                {
                    "ilo_name": "DAY & NITE TOWING",
                    "vips_impound_lot_operator_id": 159
                },
                {
                    "ilo_name": "DEL ORO TOWING",
                    "vips_impound_lot_operator_id": 266
                },
                {
                    "ilo_name": "DOLLAR TOWING",
                    "vips_impound_lot_operator_id": 113
                },
                {
                    "ilo_name": "DON'S AUTO TOWING",
                    "vips_impound_lot_operator_id": 39
                },
                {
                    "ilo_name": "DRAKE TOWING",
                    "vips_impound_lot_operator_id": 384
                },
                {
                    "ilo_name": "DUNN RIGHT TOWING & RECOVERY",
                    "vips_impound_lot_operator_id": 22
                },
                {
                    "ilo_name": "EAGLE EYE MARINE SERVICES",
                    "vips_impound_lot_operator_id": 335
                },
                {
                    "ilo_name": "EAGLE ROCK TOWING (ARMSTRONG)",
                    "vips_impound_lot_operator_id": 351
                },
                {
                    "ilo_name": "EAGLE ROCK TOWING (SALMON ARM)",
                    "vips_impound_lot_operator_id": 369
                },
                {
                    "ilo_name": "EAGLE ROCK TOWING (SICAMOUS)",
                    "vips_impound_lot_operator_id": 352
                },
                {
                    "ilo_name": "EFM TOWING",
                    "vips_impound_lot_operator_id": 357
                },
                {
                    "ilo_name": "EISENKRIEN SERVICES",
                    "vips_impound_lot_operator_id": 362
                },
                {
                    "ilo_name": "ENCORE TOWING & SERVICE",
                    "vips_impound_lot_operator_id": 59
                },
                {
                    "ilo_name": "EXCEPTIONAL TOWING & RECOVERY",
                    "vips_impound_lot_operator_id": 246
                },
                {
                    "ilo_name": "FIRST CHOICE TOWING",
                    "vips_impound_lot_operator_id": 344
                },
                {
                    "ilo_name": "FREIGHTLINER OF CRANBROOK",
                    "vips_impound_lot_operator_id": 293
                },
                {
                    "ilo_name": "GAMMOND TOWING",
                    "vips_impound_lot_operator_id": 997
                },
                {
                    "ilo_name": "GARRICK AUTOMOTIVE",
                    "vips_impound_lot_operator_id": 386
                },
                {
                    "ilo_name": "GATEWAY TOWING & RECOVERY",
                    "vips_impound_lot_operator_id": 316
                },
                {
                    "ilo_name": "GEM TOWING",
                    "vips_impound_lot_operator_id": 237
                },
                {
                    "ilo_name": "GEORGIA STRAIGHT TOWING",
                    "vips_impound_lot_operator_id": 48
                },
                {
                    "ilo_name": "GINO'S TOWING",
                    "vips_impound_lot_operator_id": 840
                },
                {
                    "ilo_name": "GIVER A YANK TOWING",
                    "vips_impound_lot_operator_id": 330
                },
                {
                    "ilo_name": "GOOD SHEPHERD TOWING",
                    "vips_impound_lot_operator_id": 841
                },
                {
                    "ilo_name": "GRANTON MOTORS",
                    "vips_impound_lot_operator_id": 171
                },
                {
                    "ilo_name": "GRASS CREEK VENTURES",
                    "vips_impound_lot_operator_id": 327
                },
                {
                    "ilo_name": "HOGIES TOWING",
                    "vips_impound_lot_operator_id": 11
                },
                {
                    "ilo_name": "HOPE TOWING",
                    "vips_impound_lot_operator_id": 361
                },
                {
                    "ilo_name": "ISLAND THUNDER TOWING",
                    "vips_impound_lot_operator_id": 359
                },
                {
                    "ilo_name": "J D TOWING",
                    "vips_impound_lot_operator_id": 60
                },
                {
                    "ilo_name": "JACK'S TOWING (ABBOTSFORD)",
                    "vips_impound_lot_operator_id": 64
                },
                {
                    "ilo_name": "JACK'S TOWING (MISSION)",
                    "vips_impound_lot_operator_id": 395
                },
                {
                    "ilo_name": "JAMIE DAVIS TOWING (GOLDEN)",
                    "vips_impound_lot_operator_id": 957
                },
                {
                    "ilo_name": "JAMIE DAVIS TOWING (HOPE)",
                    "vips_impound_lot_operator_id": 314
                },
                {
                    "ilo_name": "JAY'S CUSTOM TOWING",
                    "vips_impound_lot_operator_id": 303
                },
                {
                    "ilo_name": "JIMCO TOWING",
                    "vips_impound_lot_operator_id": 257
                },
                {
                    "ilo_name": "KBM AUTOWORKS & TOWING",
                    "vips_impound_lot_operator_id": 199
                },
                {
                    "ilo_name": "KEEGZ SOUTH COUNTRY TOWING",
                    "vips_impound_lot_operator_id": 281
                },
                {
                    "ilo_name": "KMB AUTOBODY",
                    "vips_impound_lot_operator_id": 87
                },
                {
                    "ilo_name": "KOMAR TOWING",
                    "vips_impound_lot_operator_id": 275
                },
                {
                    "ilo_name": "KOOL COUNTRY AUTO PARTS TOWING & RADS",
                    "vips_impound_lot_operator_id": 164
                },
                {
                    "ilo_name": "KOOTENAY TOWING",
                    "vips_impound_lot_operator_id": 270
                },
                {
                    "ilo_name": "L J'S TOWING & TRANSPORT",
                    "vips_impound_lot_operator_id": 140
                },
                {
                    "ilo_name": "LANE'S AUTO TOWING",
                    "vips_impound_lot_operator_id": 47
                },
                {
                    "ilo_name": "LARSEN TOWING",
                    "vips_impound_lot_operator_id": 1259
                },
                {
                    "ilo_name": "LILLOOET AUTOBODY & TOWING",
                    "vips_impound_lot_operator_id": 372
                },
                {
                    "ilo_name": "LITTLE MOUNTAIN TOWING",
                    "vips_impound_lot_operator_id": 1217
                },
                {
                    "ilo_name": "LONG BEACH TOWING",
                    "vips_impound_lot_operator_id": 1337
                },
                {
                    "ilo_name": "MAC'S TOWING (MISSION)",
                    "vips_impound_lot_operator_id": 379
                },
                {
                    "ilo_name": "MAC'S TOWING (NEW HAZELTON)",
                    "vips_impound_lot_operator_id": 877
                },
                {
                    "ilo_name": "MAPLE RIDGE TOWING",
                    "vips_impound_lot_operator_id": 326
                },
                {
                    "ilo_name": "MARIO'S TOWING (HOPE)",
                    "vips_impound_lot_operator_id": 390
                },
                {
                    "ilo_name": "MARIO'S TOWING (KAMLOOPS)",
                    "vips_impound_lot_operator_id": 392
                },
                {
                    "ilo_name": "MARIO'S TOWING (KELOWNA)",
                    "vips_impound_lot_operator_id": 203
                },
                {
                    "ilo_name": "MARIO'S TOWING (MERRITT)",
                    "vips_impound_lot_operator_id": 309
                },
                {
                    "ilo_name": "MARIO'S TOWING (PRINCETON)",
                    "vips_impound_lot_operator_id": 268
                },
                {
                    "ilo_name": "MARIO'S TOWING (WEST KELOWNA)",
                    "vips_impound_lot_operator_id": 266
                },
                {
                    "ilo_name": "MAYNE ISLAND TOWING",
                    "vips_impound_lot_operator_id": 1397
                },
                {
                    "ilo_name": "MCBRIDE'S TOWING",
                    "vips_impound_lot_operator_id": 99
                },
                {
                    "ilo_name": "ME & RON'S TOWING",
                    "vips_impound_lot_operator_id": 145
                },
                {
                    "ilo_name": "MECHAM SALES & SERVICE",
                    "vips_impound_lot_operator_id": 167
                },
                {
                    "ilo_name": "MERRITT JJ'S TOWING & RECOVERY",
                    "vips_impound_lot_operator_id": 74
                },
                {
                    "ilo_name": "MID ISLAND TOWING",
                    "vips_impound_lot_operator_id": 79
                },
                {
                    "ilo_name": "MID-NYTES TOWING",
                    "vips_impound_lot_operator_id": 187
                },
                {
                    "ilo_name": "MIKE'S AUTOMOTIVE SERVICES",
                    "vips_impound_lot_operator_id": 295
                },
                {
                    "ilo_name": "MILL BAY TOWING",
                    "vips_impound_lot_operator_id": 80
                },
                {
                    "ilo_name": "MISSION TOWING (AGASSIZ)",
                    "vips_impound_lot_operator_id": 817
                },
                {
                    "ilo_name": "MISSION TOWING (MISSION)",
                    "vips_impound_lot_operator_id": 395
                },
                {
                    "ilo_name": "MITCHELL'S TOWING (NORTH VAN)",
                    "vips_impound_lot_operator_id": 366
                },
                {
                    "ilo_name": "MITCHELL'S TOWING (VANCOUVER)",
                    "vips_impound_lot_operator_id": 366
                },
                {
                    "ilo_name": "MONASHEE MOTORS",
                    "vips_impound_lot_operator_id": 215
                },
                {
                    "ilo_name": "MUNDIE'S TOWING (BURNABY)",
                    "vips_impound_lot_operator_id": 136
                },
                {
                    "ilo_name": "MUNDIE'S TOWING (COQUITLAM)",
                    "vips_impound_lot_operator_id": 136
                },
                {
                    "ilo_name": "MUNDIE'S TOWING (DELTA)",
                    "vips_impound_lot_operator_id": 136
                },
                {
                    "ilo_name": "MUNDIE'S TOWING (NEW WEST)",
                    "vips_impound_lot_operator_id": 136
                },
                {
                    "ilo_name": "MUNDIE'S TOWING (RICHMOND)",
                    "vips_impound_lot_operator_id": 136
                },
                {
                    "ilo_name": "MUNDIE'S TOWING (SURREY)",
                    "vips_impound_lot_operator_id": 136
                },
                {
                    "ilo_name": "MUNDIE'S TOWING (VANCOUVER)",
                    "vips_impound_lot_operator_id": 136
                },
                {
                    "ilo_name": "NANOOSE BAY TOWING",
                    "vips_impound_lot_operator_id": 182
                },
                {
                    "ilo_name": "NORTH NAKUSP TOWING",
                    "vips_impound_lot_operator_id": 175
                },
                {
                    "ilo_name": "NORTH RIVER TOWING",
                    "vips_impound_lot_operator_id": 198
                },
                {
                    "ilo_name": "NORTHERN CAPITAL TOWING",
                    "vips_impound_lot_operator_id": 169
                },
                {
                    "ilo_name": "O'BRIEN'S SERVICE & REPAIRS",
                    "vips_impound_lot_operator_id": 322
                },
                {
                    "ilo_name": "O'CONNOR MOTORS",
                    "vips_impound_lot_operator_id": 251
                },
                {
                    "ilo_name": "OK REGION TOWING (PENTICTON)",
                    "vips_impound_lot_operator_id": 380
                },
                {
                    "ilo_name": "OK REGION TOWING (SUMMERLAND)",
                    "vips_impound_lot_operator_id": 380
                },
                {
                    "ilo_name": "ON CALL TOWING & TRAFFIC CONTROL",
                    "vips_impound_lot_operator_id": 206
                },
                {
                    "ilo_name": "PARKSVILLE TOWING",
                    "vips_impound_lot_operator_id": 63
                },
                {
                    "ilo_name": "PARTEL TOWING & RECOVERY",
                    "vips_impound_lot_operator_id": 239
                },
                {
                    "ilo_name": "PAYLESS TOWING (NORTH VAN)",
                    "vips_impound_lot_operator_id": 129
                },
                {
                    "ilo_name": "PAYLESS TOWING (PEMBERTON)",
                    "vips_impound_lot_operator_id": 245
                },
                {
                    "ilo_name": "PAYLESS TOWING (SQUAMISH)",
                    "vips_impound_lot_operator_id": 218
                },
                {
                    "ilo_name": "PAYLESS TOWING (WHISTLER)",
                    "vips_impound_lot_operator_id": 218
                },
                {
                    "ilo_name": "PENINSULA TOWING",
                    "vips_impound_lot_operator_id": 36
                },
                {
                    "ilo_name": "PENTICTON TOWING",
                    "vips_impound_lot_operator_id": 131
                },
                {
                    "ilo_name": "PETRO CANADA TOWING",
                    "vips_impound_lot_operator_id": 518
                },
                {
                    "ilo_name": "PIONEER MOTORS",
                    "vips_impound_lot_operator_id": 54
                },
                {
                    "ilo_name": "PIRATE TOWING",
                    "vips_impound_lot_operator_id": 757
                },
                {
                    "ilo_name": "PRISM TOWING",
                    "vips_impound_lot_operator_id": 216
                },
                {
                    "ilo_name": "PRONTO TOWING",
                    "vips_impound_lot_operator_id": 292
                },
                {
                    "ilo_name": "PROTOW",
                    "vips_impound_lot_operator_id": 24
                },
                {
                    "ilo_name": "QUIRING MOTORS",
                    "vips_impound_lot_operator_id": 92
                },
                {
                    "ilo_name": "RELIABLE TOWING (MERRITT)",
                    "vips_impound_lot_operator_id": 74
                },
                {
                    "ilo_name": "RELIABLE TOWING (MISSION)",
                    "vips_impound_lot_operator_id": 395
                },
                {
                    "ilo_name": "RELIABLE TOWING (PRINCETON)",
                    "vips_impound_lot_operator_id": 1257
                },
                {
                    "ilo_name": "REZILLIANT TOWING (FORT NELSON)",
                    "vips_impound_lot_operator_id": 1077
                },
                {
                    "ilo_name": "REZILLIANT TOWING (FORT ST JOHN)",
                    "vips_impound_lot_operator_id": 396
                },
                {
                    "ilo_name": "RICH BOYZ MECHANICAL",
                    "vips_impound_lot_operator_id": 397
                },
                {
                    "ilo_name": "ROADHOUSE TOWING",
                    "vips_impound_lot_operator_id": 331
                },
                {
                    "ilo_name": "ROADKILL TOWING",
                    "vips_impound_lot_operator_id": 1237
                },
                {
                    "ilo_name": "ROADWAY TOWING",
                    "vips_impound_lot_operator_id": 382
                },
                {
                    "ilo_name": "ROBERT'S TOWING",
                    "vips_impound_lot_operator_id": 146
                },
                {
                    "ilo_name": "RON'S TOWING",
                    "vips_impound_lot_operator_id": 17
                },
                {
                    "ilo_name": "RUPERT TOWING",
                    "vips_impound_lot_operator_id": 14
                },
                {
                    "ilo_name": "RUSTY'S TOWING",
                    "vips_impound_lot_operator_id": 100
                },
                {
                    "ilo_name": "SCRAP KING AUTO WRECKING & TOWING (CRESTON)",
                    "vips_impound_lot_operator_id": 278
                },
                {
                    "ilo_name": "SCRAP KING AUTO WRECKING & TOWING (SALMO)",
                    "vips_impound_lot_operator_id": 280
                },
                {
                    "ilo_name": "SKOOKUM TOWING",
                    "vips_impound_lot_operator_id": 205
                },
                {
                    "ilo_name": "SMOKEY CREEK SALVAGE",
                    "vips_impound_lot_operator_id": 190
                },
                {
                    "ilo_name": "SOOKE TOWING",
                    "vips_impound_lot_operator_id": 89
                },
                {
                    "ilo_name": "SORRENTO TOWING & RECOVERY",
                    "vips_impound_lot_operator_id": 174
                },
                {
                    "ilo_name": "SPARWOOD TOWING (FERNIE)",
                    "vips_impound_lot_operator_id": 192
                },
                {
                    "ilo_name": "SPARWOOD TOWING (SPARWOOD)",
                    "vips_impound_lot_operator_id": 42
                },
                {
                    "ilo_name": "SPECIALIZED TOWING",
                    "vips_impound_lot_operator_id": 148
                },
                {
                    "ilo_name": "SPEEDWAY TOWING",
                    "vips_impound_lot_operator_id": 418
                },
                {
                    "ilo_name": "TERRY'S TOWING SERVICE",
                    "vips_impound_lot_operator_id": 320
                },
                {
                    "ilo_name": "THUNDER VALLEY TOWING",
                    "vips_impound_lot_operator_id": 208
                },
                {
                    "ilo_name": "TIGER TOWING",
                    "vips_impound_lot_operator_id": 302
                },
                {
                    "ilo_name": "TJ'S TOWING & STORAGE",
                    "vips_impound_lot_operator_id": 247
                },
                {
                    "ilo_name": "TLC AUTOMOTIVE SERVICES",
                    "vips_impound_lot_operator_id": 234
                },
                {
                    "ilo_name": "TOTEM TOWING",
                    "vips_impound_lot_operator_id": 304
                },
                {
                    "ilo_name": "TYLER'S TOWING",
                    "vips_impound_lot_operator_id": 70
                },
                {
                    "ilo_name": "UNITOW (SURREY)",
                    "vips_impound_lot_operator_id": 116
                },
                {
                    "ilo_name": "UNITOW (VANCOUVER)",
                    "vips_impound_lot_operator_id": 126
                },
                {
                    "ilo_name": "VAN HORNE TOWING",
                    "vips_impound_lot_operator_id": 44
                },
                {
                    "ilo_name": "VERNON AUTO TOWING",
                    "vips_impound_lot_operator_id": 119
                },
                {
                    "ilo_name": "WALLY'S AUTOBODY",
                    "vips_impound_lot_operator_id": 120
                },
                {
                    "ilo_name": "WALT'S TOWING",
                    "vips_impound_lot_operator_id": 135
                },
                {
                    "ilo_name": "WARBRICK TOWING & SALVAGE",
                    "vips_impound_lot_operator_id": 45
                },
                {
                    "ilo_name": "WAYNE'S TOWING",
                    "vips_impound_lot_operator_id": 121
                },
                {
                    "ilo_name": "WESTERN AUTOWRECKERS",
                    "vips_impound_lot_operator_id": 160
                },
                {
                    "ilo_name": "WESTSHORE TOWING",
                    "vips_impound_lot_operator_id": 354
                },
                {
                    "ilo_name": "WHITE KNIGHT AUTO RESCUE",
                    "vips_impound_lot_operator_id": 165
                },
                {
                    "ilo_name": "WRENCH BENDER TOWING",
                    "vips_impound_lot_operator_id": 336
                },
                {
                    "ilo_name": "ZIGGY'S TOWING",
                    "vips_impound_lot_operator_id": 391
                }
            ]
        )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ilo_cross_ref')
    # ### end Alembic commands ###
