"""empty message

Revision ID: 25ad6d340253
Revises: 9cb2bdb96393
Create Date: 2023-11-26 12:15:28.221377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ad6d340253'
down_revision = '9cb2bdb96393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_processing_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('task_processing_status')

    # ### end Alembic commands ###
