"""mv6020

Revision ID: 2c51e711695d
Revises: b183aabe0707
Create Date: 2025-07-09 14:35:09.584309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c51e711695d'
down_revision = 'b183aabe0707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collision_location',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('contributing_factors',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('damage_location',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('damage_severity',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('ejection',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('entity_type',
    sa.Column('code', sa.String(length=1), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('injury_classification',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('injury_location',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('injury_type',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('land_usage',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('lighting_condition',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('location_of_first_contact',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('pedestrian_action',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('pedestrian_location',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('position',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('pre_collision_action',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('primary_collision_occurrence',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('road_class',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('road_type',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('roadway_character',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('roadway_condition',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('safety_equipment',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('speed_zone',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('taken_by',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('taken_to',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('traffic_control',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('traffic_flow',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('type_of_collision',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('vehicle_type',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('vehicle_use',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('victim_status',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('weather_condition',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='TAR'
    )
    op.create_table('submission',
    sa.Column('submission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ff_application_id', sa.Integer(), nullable=False),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('task_processing_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_guid'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('collision',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('collision_case_num', sa.String(length=10), nullable=False),
    sa.Column('collision_scenario', sa.String(length=2), nullable=False),
    sa.Column('police_file_num', sa.String(length=18), nullable=False),
    sa.Column('prime_file_vjur', sa.Integer(), nullable=False),
    sa.Column('police_file_prefix', sa.String(length=15), nullable=True),
    sa.Column('date_collision', sa.Date(), nullable=False),
    sa.Column('time_collision', sa.Time(), nullable=False),
    sa.Column('reported_same_day', sa.Boolean(), nullable=False),
    sa.Column('time_collision_unknown', sa.Boolean(), nullable=False),
    sa.Column('date_reported', sa.Date(), nullable=False),
    sa.Column('hit_and_run', sa.String(length=1), nullable=False),
    sa.Column('police_attended', sa.String(length=1), nullable=False),
    sa.Column('police_agency_type_district', sa.String(length=30), nullable=False),
    sa.Column('police_agency_code', sa.Integer(), nullable=False),
    sa.Column('police_zone', sa.String(length=22), nullable=True),
    sa.Column('primary_collision_occ_code', sa.String(length=2), nullable=False),
    sa.Column('first_contact_event', sa.String(length=2), nullable=False),
    sa.Column('first_contact_loc', sa.String(length=2), nullable=False),
    sa.Column('has_countable_fatal', sa.String(length=2), nullable=False),
    sa.Column('countable_fatal_total', sa.Integer(), nullable=False),
    sa.Column('completed_by_name', sa.String(length=35), nullable=False),
    sa.Column('completed_by_id', sa.String(length=40), nullable=False),
    sa.Column('detachment_unit', sa.String(length=30), nullable=False),
    sa.Column('icbc_submission_date', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=40), nullable=True),
    sa.Column('investigated_by_traffic_analyst', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_id'], ['user.user_guid'], ),
    sa.ForeignKeyConstraint(['first_contact_event'], ['TAR.type_of_collision.code'], ),
    sa.ForeignKeyConstraint(['first_contact_loc'], ['TAR.location_of_first_contact.code'], ),
    sa.ForeignKeyConstraint(['police_agency_code'], ['agency.id'], ),
    sa.ForeignKeyConstraint(['primary_collision_occ_code'], ['TAR.primary_collision_occurrence.code'], ),
    sa.ForeignKeyConstraint(['prime_file_vjur'], ['agency.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.submission_id'], ),
    sa.PrimaryKeyConstraint('collision_case_num'),
    schema='TAR'
    )
    op.create_table('additional_collision_details',
    sa.Column('collision_case_num', sa.String(length=10), nullable=False),
    sa.Column('pedestrian_location', sa.String(length=2), nullable=True),
    sa.Column('pedestrian_action', sa.String(length=2), nullable=True),
    sa.Column('has_other_prop_damage', sa.String(length=2), nullable=False),
    sa.Column('other_prop_damage_desc', sa.String(length=3000), nullable=True),
    sa.Column('prop_damage_est_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('has_witnesses', sa.Boolean(), nullable=False),
    sa.Column('police_comments', sa.String(length=3000), nullable=True),
    sa.Column('collision_type', sa.String(length=2), nullable=False),
    sa.Column('total_est_damage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_injured', sa.Integer(), nullable=False),
    sa.Column('total_killed', sa.Integer(), nullable=False),
    sa.Column('total_vehicles', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collision_case_num'], ['TAR.collision.collision_case_num'], ),
    sa.ForeignKeyConstraint(['pedestrian_action'], ['TAR.pedestrian_action.code'], ),
    sa.ForeignKeyConstraint(['pedestrian_location'], ['TAR.pedestrian_location.code'], ),
    sa.PrimaryKeyConstraint('collision_case_num'),
    schema='TAR'
    )
    op.create_table('entity',
    sa.Column('entity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collision_case_num', sa.String(length=10), nullable=False),
    sa.Column('entity_type', sa.String(length=1), nullable=False),
    sa.Column('entity_num', sa.Integer(), nullable=False),
    sa.Column('possible_offender', sa.String(length=1), nullable=False),
    sa.Column('vehicle_parked', sa.Boolean(), nullable=True),
    sa.Column('unknown_entity', sa.Boolean(), nullable=True),
    sa.Column('driver_license_num', sa.String(length=25), nullable=True),
    sa.Column('license_prov_state', sa.String(length=2), nullable=True),
    sa.Column('license_expiry', sa.Integer(), nullable=True),
    sa.Column('surname', sa.String(length=28), nullable=True),
    sa.Column('given_name', sa.String(length=25), nullable=True),
    sa.Column('license_class', sa.String(length=10), nullable=True),
    sa.Column('graduated_license_type', sa.String(length=1), nullable=True),
    sa.Column('residential_address', sa.String(length=90), nullable=True),
    sa.Column('business_address', sa.String(length=68), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age_at_collision', sa.Integer(), nullable=True),
    sa.Column('contact_phone_num', sa.String(length=25), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('contributing_factor_1', sa.String(length=2), nullable=False),
    sa.Column('contributing_factor_2', sa.String(length=2), nullable=False),
    sa.Column('contributing_factor_3', sa.String(length=2), nullable=False),
    sa.Column('contributing_factor_4', sa.String(length=2), nullable=False),
    sa.Column('charges_blood_alc_tests_taken', sa.Boolean(), nullable=True),
    sa.Column('blood_alc_test', sa.String(length=3), nullable=True),
    sa.Column('result_1', sa.String(length=8), nullable=True),
    sa.Column('result_2', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['collision_case_num'], ['TAR.collision.collision_case_num'], ),
    sa.ForeignKeyConstraint(['contributing_factor_1'], ['TAR.contributing_factors.code'], ),
    sa.ForeignKeyConstraint(['contributing_factor_2'], ['TAR.contributing_factors.code'], ),
    sa.ForeignKeyConstraint(['contributing_factor_3'], ['TAR.contributing_factors.code'], ),
    sa.ForeignKeyConstraint(['contributing_factor_4'], ['TAR.contributing_factors.code'], ),
    sa.ForeignKeyConstraint(['entity_type'], ['TAR.entity_type.code'], ),
    sa.PrimaryKeyConstraint('entity_id'),
    schema='TAR'
    )
    op.create_table('location',
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collision_case_num', sa.String(), nullable=False),
    sa.Column('hwy_code', sa.String(), nullable=False),
    sa.Column('hwy_route_num', sa.String(length=4), nullable=True),
    sa.Column('segment_num', sa.String(length=4), nullable=True),
    sa.Column('loc_code_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('city_name', sa.String(), nullable=False),
    sa.Column('city_status', sa.String(length=30), nullable=True),
    sa.Column('street_on', sa.String(length=255), nullable=True),
    sa.Column('street_at', sa.String(length=255), nullable=True),
    sa.Column('street_desc', sa.String(length=60), nullable=True),
    sa.Column('gps_format', sa.String(length=1), nullable=True),
    sa.Column('lat_decim_degrees', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('long_decim_degrees', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lat_degree', sa.Integer(), nullable=True),
    sa.Column('lat_min', sa.Integer(), nullable=True),
    sa.Column('lat_sec', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('long_degree', sa.Integer(), nullable=True),
    sa.Column('long_min', sa.Integer(), nullable=True),
    sa.Column('long_sec', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('road_class', sa.String(length=2), nullable=False),
    sa.Column('traffic_flow', sa.String(length=2), nullable=False),
    sa.Column('collision_loc', sa.String(length=2), nullable=False),
    sa.Column('primary_speed_zone', sa.String(length=3), nullable=False),
    sa.Column('secondary_speed_zone', sa.String(length=3), nullable=True),
    sa.Column('land_usage', sa.String(length=2), nullable=False),
    sa.Column('road_type', sa.String(length=2), nullable=False),
    sa.Column('traffic_control', sa.String(length=2), nullable=True),
    sa.Column('roadway_character', sa.String(length=2), nullable=False),
    sa.Column('roadway_surface_cond', sa.String(length=2), nullable=False),
    sa.Column('weather_cond', sa.String(length=2), nullable=False),
    sa.Column('lighting_cond', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['collision_case_num'], ['TAR.collision.collision_case_num'], ),
    sa.ForeignKeyConstraint(['collision_loc'], ['TAR.collision_location.code'], ),
    sa.ForeignKeyConstraint(['land_usage'], ['TAR.land_usage.code'], ),
    sa.ForeignKeyConstraint(['lighting_cond'], ['TAR.lighting_condition.code'], ),
    sa.ForeignKeyConstraint(['primary_speed_zone'], ['TAR.speed_zone.code'], ),
    sa.ForeignKeyConstraint(['road_class'], ['TAR.road_class.code'], ),
    sa.ForeignKeyConstraint(['road_type'], ['TAR.road_type.code'], ),
    sa.ForeignKeyConstraint(['roadway_character'], ['TAR.roadway_character.code'], ),
    sa.ForeignKeyConstraint(['roadway_surface_cond'], ['TAR.roadway_condition.code'], ),
    sa.ForeignKeyConstraint(['secondary_speed_zone'], ['TAR.speed_zone.code'], ),
    sa.ForeignKeyConstraint(['traffic_control'], ['TAR.traffic_control.code'], ),
    sa.ForeignKeyConstraint(['traffic_flow'], ['TAR.traffic_flow.code'], ),
    sa.ForeignKeyConstraint(['weather_cond'], ['TAR.weather_condition.code'], ),
    sa.PrimaryKeyConstraint('location_id'),
    schema='TAR'
    )
    op.create_table('witness_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collision_case_num', sa.String(length=10), nullable=False),
    sa.Column('witness_name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_phn_num', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['collision_case_num'], ['TAR.collision.collision_case_num'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='TAR'
    )
    op.create_table('charges',
    sa.Column('charge_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('charge_type', sa.String(length=1), nullable=True),
    sa.Column('section_num', sa.String(length=10), nullable=True),
    sa.Column('offence_title', sa.String(length=70), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['TAR.entity.entity_id'], ),
    sa.PrimaryKeyConstraint('charge_id'),
    schema='TAR'
    )
    op.create_table('entity_vehicle',
    sa.Column('vehicle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_plate_num', sa.String(length=20), nullable=True),
    sa.Column('vehicle_plate_prov_state', sa.String(length=2), nullable=True),
    sa.Column('vehicle_year', sa.String(length=4), nullable=True),
    sa.Column('vehicle_make', sa.String(length=30), nullable=True),
    sa.Column('vehicle_style', sa.String(length=15), nullable=True),
    sa.Column('trailer_towed_plate_num', sa.String(length=20), nullable=True),
    sa.Column('trailer_towed_plate_prov_state', sa.String(length=2), nullable=True),
    sa.Column('is_registered_owner', sa.Boolean(), nullable=True),
    sa.Column('vehicle_owner_name', sa.String(length=60), nullable=True),
    sa.Column('vehicle_owner_address', sa.String(length=90), nullable=True),
    sa.Column('nsc_num', sa.String(length=50), nullable=True),
    sa.Column('jur_code', sa.String(length=45), nullable=True),
    sa.Column('damage_location_code', sa.String(length=2), nullable=False),
    sa.Column('severety_code', sa.String(length=2), nullable=False),
    sa.Column('estimated_vehicle_damage', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('vehicle_stolen', sa.String(length=1), nullable=True),
    sa.Column('vehicle_towed', sa.String(length=1), nullable=True),
    sa.Column('vehicle_towed_by', sa.String(length=30), nullable=True),
    sa.Column('dir_of_travel', sa.String(length=1), nullable=True),
    sa.Column('entity_street', sa.String(length=60), nullable=True),
    sa.Column('insurance_coverage', sa.String(length=1), nullable=True),
    sa.Column('other_insurer', sa.String(length=20), nullable=True),
    sa.Column('other_insurance_policy_num', sa.String(length=20), nullable=True),
    sa.Column('second_contact', sa.String(length=2), nullable=True),
    sa.Column('pre_collision_vehicle_action_first_event', sa.String(length=2), nullable=True),
    sa.Column('vehicle_type', sa.String(length=2), nullable=True),
    sa.Column('vehicle_use', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['damage_location_code'], ['TAR.damage_location.code'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['TAR.entity.entity_id'], ),
    sa.ForeignKeyConstraint(['pre_collision_vehicle_action_first_event'], ['TAR.pre_collision_action.code'], ),
    sa.ForeignKeyConstraint(['second_contact'], ['TAR.type_of_collision.code'], ),
    sa.ForeignKeyConstraint(['severety_code'], ['TAR.damage_severity.code'], ),
    sa.ForeignKeyConstraint(['vehicle_type'], ['TAR.vehicle_type.code'], ),
    sa.ForeignKeyConstraint(['vehicle_use'], ['TAR.vehicle_use.code'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    schema='TAR'
    )
    op.create_table('involved_person',
    sa.Column('person_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('given_name', sa.String(length=30), nullable=True),
    sa.Column('vehicle_occupied', sa.String(length=2), nullable=True),
    sa.Column('position_of_person', sa.String(length=2), nullable=False),
    sa.Column('safety_equipment_used', sa.String(length=2), nullable=False),
    sa.Column('ejection_from_vehicle', sa.String(length=2), nullable=False),
    sa.Column('age', sa.String(length=10), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('severe_injury_location', sa.String(length=2), nullable=False),
    sa.Column('injury_type', sa.String(length=2), nullable=False),
    sa.Column('consciousness_state', sa.String(length=2), nullable=True),
    sa.Column('injured_taken_to', sa.String(length=4), nullable=True),
    sa.Column('injured_taken_by', sa.String(length=4), nullable=True),
    sa.Column('injury_classification', sa.String(length=2), nullable=True),
    sa.Column('date_of_death', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['consciousness_state'], ['TAR.victim_status.code'], ),
    sa.ForeignKeyConstraint(['ejection_from_vehicle'], ['TAR.ejection.code'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['TAR.entity.entity_id'], ),
    sa.ForeignKeyConstraint(['injured_taken_by'], ['TAR.taken_by.code'], ),
    sa.ForeignKeyConstraint(['injured_taken_to'], ['TAR.taken_to.code'], ),
    sa.ForeignKeyConstraint(['injury_classification'], ['TAR.injury_classification.code'], ),
    sa.ForeignKeyConstraint(['injury_type'], ['TAR.injury_type.code'], ),
    sa.ForeignKeyConstraint(['position_of_person'], ['TAR.position.code'], ),
    sa.ForeignKeyConstraint(['safety_equipment_used'], ['TAR.safety_equipment.code'], ),
    sa.ForeignKeyConstraint(['severe_injury_location'], ['TAR.injury_location.code'], ),
    sa.PrimaryKeyConstraint('person_id'),
    schema='TAR'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('involved_person', schema='TAR')
    op.drop_table('entity_vehicle', schema='TAR')
    op.drop_table('charges', schema='TAR')
    op.drop_table('witness_info', schema='TAR')
    op.drop_table('location', schema='TAR')
    op.drop_table('entity', schema='TAR')
    op.drop_table('additional_collision_details', schema='TAR')
    op.drop_table('collision', schema='TAR')
    op.drop_table('submission')
    op.drop_table('weather_condition', schema='TAR')
    op.drop_table('victim_status', schema='TAR')
    op.drop_table('vehicle_use', schema='TAR')
    op.drop_table('vehicle_type', schema='TAR')
    op.drop_table('type_of_collision', schema='TAR')
    op.drop_table('traffic_flow', schema='TAR')
    op.drop_table('traffic_control', schema='TAR')
    op.drop_table('taken_to', schema='TAR')
    op.drop_table('taken_by', schema='TAR')
    op.drop_table('speed_zone', schema='TAR')
    op.drop_table('safety_equipment', schema='TAR')
    op.drop_table('roadway_condition', schema='TAR')
    op.drop_table('roadway_character', schema='TAR')
    op.drop_table('road_type', schema='TAR')
    op.drop_table('road_class', schema='TAR')
    op.drop_table('primary_collision_occurrence', schema='TAR')
    op.drop_table('pre_collision_action', schema='TAR')
    op.drop_table('position', schema='TAR')
    op.drop_table('pedestrian_location', schema='TAR')
    op.drop_table('pedestrian_action', schema='TAR')
    op.drop_table('location_of_first_contact', schema='TAR')
    op.drop_table('lighting_condition', schema='TAR')
    op.drop_table('land_usage', schema='TAR')
    op.drop_table('injury_type', schema='TAR')
    op.drop_table('injury_location', schema='TAR')
    op.drop_table('injury_classification', schema='TAR')
    op.drop_table('entity_type', schema='TAR')
    op.drop_table('ejection', schema='TAR')
    op.drop_table('damage_severity', schema='TAR')
    op.drop_table('damage_location', schema='TAR')
    op.drop_table('contributing_factors', schema='TAR')
    op.drop_table('collision_location', schema='TAR')
    # ### end Alembic commands ###
