"""police_agency_code_string

Revision ID: 39620e94361d
Revises: b5039cb318db
Create Date: 2026-02-23 11:24:42.935196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39620e94361d'
down_revision = 'b5039cb318db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collision', schema='TAR') as batch_op:
        batch_op.drop_constraint('collision_police_agency_code_fkey', type_='foreignkey')
        batch_op.alter_column('police_agency_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=False)

    with op.batch_alter_table('police_agency', schema='TAR') as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=8),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"TAR".police_agency_code_seq\'::regclass)'))

    op.execute('ALTER TABLE "TAR".collision ADD CONSTRAINT collision_police_agency_code_fkey FOREIGN KEY(police_agency_code) REFERENCES "TAR".police_agency(code)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('police_agency', schema='TAR') as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=8),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"TAR".police_agency_code_seq\'::regclass)'))

    with op.batch_alter_table('collision', schema='TAR') as batch_op:
        batch_op.alter_column('police_agency_code',
               existing_type=sa.String(length=8),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
