"""add_event_submission_fk

Revision ID: 3b493c418866
Revises: 1940b9b5da98
Create Date: 2026-05-27 12:37:43.827973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b493c418866'
down_revision = '1940b9b5da98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'submission', ['submission_id'], ['submission_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('submission_id')

    # ### end Alembic commands ###
