"""update_has_witness_col

Revision ID: 3ef0bb500f08
Revises: 07968b6c8b4d
Create Date: 2025-11-28 09:41:03.584385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef0bb500f08'
down_revision = '07968b6c8b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional_collision_details', schema='TAR') as batch_op:
        batch_op.alter_column('has_witnesses',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=10),
               existing_nullable=False)
        
    with op.batch_alter_table('additional_collision_details', schema='TAR') as batch_op:
        batch_op.execute("UPDATE \"TAR\".additional_collision_details SET has_witnesses = 'Y' WHERE has_witnesses = 'true' or has_witnesses = 'True'")
        batch_op.execute("UPDATE \"TAR\".additional_collision_details SET has_witnesses = 'N' WHERE has_witnesses = 'false' or has_witnesses = 'False'")
        batch_op.alter_column('has_witnesses',
               existing_type=sa.String(length=10),
               type_=sa.String(length=1),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional_collision_details', schema='TAR') as batch_op:
        batch_op.execute("UPDATE \"TAR\".additional_collision_details SET has_witnesses = '1' WHERE has_witnesses = 'Y'")
        batch_op.execute("UPDATE \"TAR\".additional_collision_details SET has_witnesses = '0' WHERE has_witnesses = 'N'")
        batch_op.alter_column('has_witnesses',
               existing_type=sa.String(length=1),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               postgresql_using="has_witnesses::boolean")

    # ### end Alembic commands ###
