"""refactor_user_agency

Revision ID: 425866ee9565
Revises: ae9b463e7f7a
Create Date: 2025-08-05 09:34:40.453421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425866ee9565'
down_revision = 'ae9b463e7f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('user_agency_id_fkey', 'agency', ['agency_id'], ['id'])
    op.execute(
        """
        update "user" u set agency_id = (select a.id from agency a where LOWER(u.agency) = LOWER(a.agency_name));
        """
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('agency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('agency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_agency_id_fkey', type_='foreignkey')
        batch_op.drop_column('agency_id')
        batch_op.alter_column('agency',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
