"""empty message

Revision ID: 43b7e19ba2e4
Revises: 15ff36b63f1c
Create Date: 2023-09-26 16:44:29.722852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b7e19ba2e4'
down_revision = '15ff36b63f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_storage_refs', schema=None) as batch_op:
        batch_op.alter_column('encryptiv',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_storage_refs', schema=None) as batch_op:
        batch_op.alter_column('encryptiv',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
