"""rename_collision_prefix

Revision ID: 4426dcf8e87c
Revises: b5a7ce8332dd
Create Date: 2025-08-27 14:46:57.142319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4426dcf8e87c'
down_revision = 'b5a7ce8332dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collision', schema='TAR') as batch_op:
        batch_op.execute('ALTER TABLE "TAR".collision RENAME COLUMN police_file_prefix TO collision_case_prefix;')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collision', schema='TAR') as batch_op:
        batch_op.execute('ALTER TABLE "TAR".collision RENAME COLUMN collision_case_prefix TO police_file_prefix;')

    # ### end Alembic commands ###
