"""empty message

Revision ID: 442cfd8dd544
Revises: 945bd9db1b20
Create Date: 2023-05-04 11:32:24.871938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442cfd8dd544'
down_revision = '945bd9db1b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('login', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
