"""empty message

Revision ID: 4e95b628b5c6
Revises: 0cd359646c78
Create Date: 2023-10-12 09:39:44.680412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e95b628b5c6'
down_revision = '0cd359646c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_driving', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_of_driving', sa.String(), nullable=True))

    with op.batch_alter_table('twenty_four_hour_form', schema=None) as batch_op:
        batch_op.drop_column('time_of_driving')
        batch_op.drop_column('date_of_driving')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twenty_four_hour_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_driving', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('time_of_driving', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('time_of_driving')
        batch_op.drop_column('date_of_driving')

    # ### end Alembic commands ###
