"""empty message

Revision ID: 4f2ef9f5bcd0
Revises: 0134c884845f
Create Date: 2023-11-22 18:43:06.067839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2ef9f5bcd0'
down_revision = '0134c884845f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spoiled_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('spoiled_timestamp')

    # ### end Alembic commands ###
