"""empty message

Revision ID: 529289c8081b
Revises: cbfbfa70b774
Create Date: 2023-11-07 13:22:09.543499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529289c8081b'
down_revision = 'cbfbfa70b774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_type', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vehicle_type', ['vehicle_type'], ['type_cd'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicle_type')

    # ### end Alembic commands ###
