"""charge_section_num_length

Revision ID: 5342cb8a9e88
Revises: 9b714585f62b
Create Date: 2025-10-14 14:24:57.035237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5342cb8a9e88'
down_revision = '9b714585f62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema='TAR') as batch_op:
        batch_op.alter_column('section_num',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema='TAR') as batch_op:
        batch_op.alter_column('section_num',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
