"""collision_updates

Revision ID: 56d7192bb891
Revises: 7cfcf95d637f
Create Date: 2025-08-26 09:52:54.375626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56d7192bb891'
down_revision = '7cfcf95d637f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collision', schema='TAR') as batch_op:
        batch_op.alter_column('time_collision',
               existing_type=postgresql.TIME(),
               nullable=True)

    with op.batch_alter_table('entity', schema='TAR') as batch_op:
        batch_op.alter_column('graduated_license_type',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema='TAR') as batch_op:
        batch_op.alter_column('graduated_license_type',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)

    with op.batch_alter_table('collision', schema='TAR') as batch_op:
        batch_op.alter_column('time_collision',
               existing_type=postgresql.TIME(),
               nullable=False)

    # ### end Alembic commands ###
