"""empty message

Revision ID: 666113694229
Revises: b7fc605b1a27
Create Date: 2024-02-12 13:28:00.762443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666113694229'
down_revision = 'b7fc605b1a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twelve_hour_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twelve_hour_form', schema=None) as batch_op:
        batch_op.drop_column('vehicle_location')

    # ### end Alembic commands ###
