"""add_irp_models

Revision ID: 691dbc1c9a0b
Revises: e19fe700a553
Create Date: 2026-03-24 08:32:57.577809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '691dbc1c9a0b'
down_revision = 'e19fe700a553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irp_prohibition_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('prohibition_period', sa.Integer(), nullable=False),
    sa.Column('breath_result', sa.String(length=20), nullable=False),
    sa.Column('monetary_penalty', sa.Numeric(), nullable=False),
    sa.Column('prohibition_reason', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('irp_asd_test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('irp_form_id', sa.Integer(), nullable=False),
    sa.Column('test_number', sa.Integer(), nullable=False),
    sa.Column('asd_identification', sa.String(length=20), nullable=False),
    sa.Column('serial_number', sa.String(length=20), nullable=False),
    sa.Column('test_time', sa.String(length=5), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('result_shown_to_driver', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['irp_form_id'], ['irp_form.form_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('irp_form_id', 'test_number', name='irp_asd_test_form_testnumber_uq')
    )
    with op.batch_alter_table('irp_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('irp_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('vi_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('driver_licence_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('driver_licence_class', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('driver_licence_seized', sa.String(length=5), nullable=False))
        batch_op.add_column(sa.Column('vehicle_impounded', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('irp_prohibition_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('witnessed_by_officer', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('admission_by_driver', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('independent_witness', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('reasonable_ground_other', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('time_of_suspicion', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('time_of_asd', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('refused_or_fail', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('time_of_refusal', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('right_to_second_test', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('lower_asd_prevail', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('right_to_test_different_asd', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('driver_requested_second_asd', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('reasonable_suspicion_odor_of_liquor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reasonable_suspicion_admission', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reasonable_suspicion_witnessed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reasonable_suspicion_other', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_drink', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('continuous_observation', sa.String(length=5), nullable=True))
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        
    op.execute("""
        INSERT INTO irp_prohibition_type (id,code,prohibition_period,breath_result,monetary_penalty,prohibition_reason,active,display_order) VALUES
        (2,'BACWARN7',7,'WARN',300,'because a sample of your breath on an approved screening device registered WARN, your ability ot drive si affected by alcohol, and this si your second prohibition due ot a WARN reading within a five year period.',true,2),
        (3,'BACWARN30',30,'WARN',400,'because a sample of your breath on an approved screening device registered WARN, your ability to drive si affected by alcohol, and this is your third or subsequent prohibition due to a WARN reading within a five vear period',true,3),
        (4,'BACFAIL',90,'FAIL',500,'because a sample of your breath on an approved screening device registered FAlL and your ability to drive si affected
    by alcohol.',true,4),
        (5,'BACREFUSAL',90,'REFUSAL',500,'because you failed or REFUSED, without a reasonable excuse, to comply with a demand made under the Criminal Code to provide asample of breath for analysis by means of an approved screening device.',true,5),
        (1,'BACWARN3',3,'WARN',200,'because a sample of your breath on an approved screening device registered WARN and your ability to drive si
    affected by alcohol.',true,1);
    """)        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('irp_form', schema=None) as batch_op:
        batch_op.alter_column('created_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('continuous_observation')
        batch_op.drop_column('last_drink')
        batch_op.drop_column('reasonable_suspicion_other')
        batch_op.drop_column('reasonable_suspicion_witnessed')
        batch_op.drop_column('reasonable_suspicion_admission')
        batch_op.drop_column('reasonable_suspicion_odor_of_liquor')
        batch_op.drop_column('driver_requested_second_asd')
        batch_op.drop_column('right_to_test_different_asd')
        batch_op.drop_column('lower_asd_prevail')
        batch_op.drop_column('right_to_second_test')
        batch_op.drop_column('time_of_refusal')
        batch_op.drop_column('refused_or_fail')
        batch_op.drop_column('time_of_asd')
        batch_op.drop_column('time_of_suspicion')
        batch_op.drop_column('reasonable_ground_other')
        batch_op.drop_column('independent_witness')
        batch_op.drop_column('admission_by_driver')
        batch_op.drop_column('witnessed_by_officer')
        batch_op.drop_column('irp_prohibition_type')
        batch_op.drop_column('vehicle_impounded')
        batch_op.drop_column('driver_licence_seized')
        batch_op.drop_column('gender')
        batch_op.drop_column('driver_licence_class')
        batch_op.drop_column('driver_licence_expiry')
        batch_op.drop_column('vi_number')
        batch_op.drop_column('irp_number')

    op.drop_table('irp_asd_test')
    op.drop_table('irp_prohibition_type')
    # ### end Alembic commands ###
