"""add_driver_licence_expiry_year

Revision ID: 6f736d2fcec2
Revises: cd52617ca649
Create Date: 2026-06-16 13:27:10.007935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f736d2fcec2'
down_revision = 'cd52617ca649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('irp_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_licence_expiry_year', sa.Integer(), nullable=True))
        batch_op.drop_column('driver_licence_expiry')

    with op.batch_alter_table('vi_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_licence_expiry_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vi_form', schema=None) as batch_op:
        batch_op.drop_column('driver_licence_expiry_year')

    with op.batch_alter_table('irp_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_licence_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('driver_licence_expiry_year')

    # ### end Alembic commands ###
