"""police_agency_icbc_prefix

Revision ID: 6ff005a1c1e6
Revises: 0060d115e3a8
Create Date: 2026-02-11 14:11:19.261666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff005a1c1e6'
down_revision = '0060d115e3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('police_agency', schema='TAR') as batch_op:
        batch_op.add_column(sa.Column('icbc_prefix', sa.String(length=1), nullable=True))

    with op.batch_alter_table('police_district', schema='TAR') as batch_op:
        batch_op.drop_column('prefix')

    op.execute("UPDATE \"TAR\".police_agency set icbc_prefix = 'V' where code = 402")
    op.execute("UPDATE \"TAR\".police_agency set icbc_prefix = 'B' where code = 406")
    op.execute("UPDATE \"TAR\".police_agency set icbc_prefix = 'S' where code = 403")
    op.execute("UPDATE \"TAR\".police_agency set icbc_prefix = 'C' where code = 404")
    op.execute("UPDATE \"TAR\".police_agency set icbc_prefix = 'A' where code = 401")
    op.execute("UPDATE \"TAR\".police_agency set icbc_prefix = 'W' where code = 410")
    op.execute("UPDATE \"TAR\".police_agency set icbc_prefix = 'N' where code = 409")
    op.execute("UPDATE \"TAR\".police_agency set icbc_prefix = 'P' where code = 412")
    op.execute("UPDATE \"TAR\".police_agency set icbc_prefix = 'D' where code = 407")
    op.execute("UPDATE \"TAR\".police_agency set icbc_prefix = 'M' where code = 408")
    op.execute("UPDATE \"TAR\".police_agency set icbc_prefix = 'T' where code = 411")
    op.execute("UPDATE \"TAR\".police_agency set icbc_prefix = 'U' where code = 730")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('police_district', schema='TAR') as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.VARCHAR(length=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('police_agency', schema='TAR') as batch_op:
        batch_op.drop_column('icbc_prefix')

    # ### end Alembic commands ###
