"""submission_form_ref

Revision ID: 7cfcf95d637f
Revises: 425866ee9565
Create Date: 2025-08-21 09:27:14.919216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cfcf95d637f'
down_revision = '425866ee9565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_form_refs',
    sa.Column('form_ref_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=50), nullable=False),
    sa.Column('form_id', sa.String(length=50), nullable=False),
    sa.Column('form_version', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.submission_id'], ),
    sa.PrimaryKeyConstraint('form_ref_id')
    )
    op.create_table('submission_events',
    sa.Column('submission_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_ref_id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_ref_id'], ['submission_form_refs.form_ref_id'], ),
    sa.PrimaryKeyConstraint('submission_event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_events')
    op.drop_table('submission_form_refs')
    # ### end Alembic commands ###
