"""empty message

Revision ID: 7fbf9737ddc4
Revises: 7925ac186d84
Create Date: 2023-10-20 14:46:15.294599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fbf9737ddc4'
down_revision = '7925ac186d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_released_to', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date_released', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_released', sa.String(), nullable=True))

    with op.batch_alter_table('twenty_four_hour_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasonable_ground_other_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reasonable_date_of_test', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reasonable_time_of_test', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resonable_test_used_alcohol', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reasonable_asd_expiry_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reasonable_result_alcohol', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reasonable_bac_result_mg', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resonable_approved_instrument_used', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reasonable_test_used_drugs', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reasonable_can_drive_drug', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reasonable_can_drive_alcohol', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('requested_can_drive_alcohol', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('requested_can_drive_drug', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('requested_test_used_alcohol', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('requested_test_used_drugs', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('witnessed_by_officer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('admission_by_driver', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('independent_witness', sa.Boolean(), nullable=True))
        batch_op.alter_column('vehicle_impounded',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('requested_BAC_result',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('reasonable_ground_other',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using='reasonable_ground_other::boolean')
        batch_op.drop_column('test_used_alcohol')
        batch_op.drop_column('result_alcohol')
        batch_op.drop_column('time_released')
        batch_op.drop_column('date_released')
        batch_op.drop_column('test_result_drugs')
        batch_op.drop_column('vehicle_released_to')
        batch_op.drop_column('date_of_test')
        batch_op.drop_column('reasonable_ground')
        batch_op.drop_column('asd_expiry_date')
        batch_op.drop_column('test_used_drugs')
        batch_op.drop_column('impound_lot_operator')
        batch_op.drop_column('bac_result_mg')
        batch_op.drop_column('time_of_test')
        batch_op.drop_column('requested_test_used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twenty_four_hour_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_test_used', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('time_of_test', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bac_result_mg', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('impound_lot_operator', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('test_used_drugs', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('asd_expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reasonable_ground', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_of_test', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_released_to', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('test_result_drugs', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_released', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('time_released', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('result_alcohol', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('test_used_alcohol', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('reasonable_ground_other',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('requested_BAC_result',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('vehicle_impounded',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.drop_column('independent_witness')
        batch_op.drop_column('admission_by_driver')
        batch_op.drop_column('witnessed_by_officer')
        batch_op.drop_column('requested_test_used_drugs')
        batch_op.drop_column('requested_test_used_alcohol')
        batch_op.drop_column('requested_can_drive_drug')
        batch_op.drop_column('requested_can_drive_alcohol')
        batch_op.drop_column('reasonable_can_drive_alcohol')
        batch_op.drop_column('reasonable_can_drive_drug')
        batch_op.drop_column('reasonable_test_used_drugs')
        batch_op.drop_column('resonable_approved_instrument_used')
        batch_op.drop_column('reasonable_bac_result_mg')
        batch_op.drop_column('reasonable_result_alcohol')
        batch_op.drop_column('reasonable_asd_expiry_date')
        batch_op.drop_column('resonable_test_used_alcohol')
        batch_op.drop_column('reasonable_time_of_test')
        batch_op.drop_column('reasonable_date_of_test')
        batch_op.drop_column('reasonable_ground_other_reason')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('time_released')
        batch_op.drop_column('date_released')
        batch_op.drop_column('vehicle_released_to')

    # ### end Alembic commands ###
