"""empty message

Revision ID: 88651b385c11
Revises: 4e95b628b5c6
Create Date: 2023-10-17 16:05:27.712883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88651b385c11'
down_revision = '4e95b628b5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twelve_hour_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_phone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twelve_hour_form', schema=None) as batch_op:
        batch_op.drop_column('driver_phone')

    # ### end Alembic commands ###
