"""add_tar_entity_email

Revision ID: 8da833e0d308
Revises: fa35ba99f01b
Create Date: 2026-02-23 13:46:13.919986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da833e0d308'
down_revision = 'fa35ba99f01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema='TAR') as batch_op:
        batch_op.add_column(sa.Column('contact_email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema='TAR') as batch_op:
        batch_op.drop_column('contact_email')

    # ### end Alembic commands ###
