"""add-submitted-offline-flag

Revision ID: 8fd77cf66929
Revises: 5342cb8a9e88
Create Date: 2025-11-05 16:08:50.740503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd77cf66929'
down_revision = '5342cb8a9e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_offline', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('submitted_offline')

    # ### end Alembic commands ###
