"""empty message

Revision ID: 9270689966c6
Revises: 8ffd5f19a31b
Create Date: 2023-10-21 10:39:01.062430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9270689966c6'
down_revision = '8ffd5f19a31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twenty_four_hour_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_test_used_drug', sa.String(), nullable=True))
        batch_op.drop_column('requested_test_used_drugs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twenty_four_hour_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_test_used_drugs', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('requested_test_used_drug')

    # ### end Alembic commands ###
