"""charge_description_length

Revision ID: 9b714585f62b
Revises: 0d9df346b27d
Create Date: 2025-10-14 11:20:26.583264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b714585f62b'
down_revision = '0d9df346b27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema='TAR') as batch_op:
        batch_op.alter_column('offence_title',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=4000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema='TAR') as batch_op:
        batch_op.alter_column('offence_title',
               existing_type=sa.String(length=4000),
               type_=sa.VARCHAR(length=70),
               existing_nullable=True)

    # ### end Alembic commands ###
