"""add_ilo_info_to_tar_entity

Revision ID: a3ea854753c0
Revises: d8a9807b33a8
Create Date: 2026-03-11 12:21:57.928793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ea854753c0'
down_revision = 'd8a9807b33a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema='TAR') as batch_op:
        batch_op.add_column(sa.Column('ilo_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ilo_address', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('ilo_city', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('ilo_phone_num', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema='TAR') as batch_op:
        batch_op.drop_column('ilo_phone_num')
        batch_op.drop_column('ilo_city')
        batch_op.drop_column('ilo_address')
        batch_op.drop_column('ilo_name')

    # ### end Alembic commands ###
