"""empty message

Revision ID: aa67792cf1b8
Revises: 1920269671bc
Create Date: 2023-11-02 17:22:39.869228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa67792cf1b8'
down_revision = '1920269671bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vi_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('out_of_province_dl_jurisdiction', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vi_form', schema=None) as batch_op:
        batch_op.drop_column('out_of_province_dl_jurisdiction')

    # ### end Alembic commands ###
