"""refactor_agency_p2

Revision ID: ae9b463e7f7a
Revises: c33984651d3c
Create Date: 2025-08-01 15:33:28.595599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9b463e7f7a'
down_revision = 'c33984651d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("update agency_cross_refs acr set agency_id = null;")

    with op.batch_alter_table('agency_cross_refs', schema=None) as batch_op:
        batch_op.alter_column('agency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    with op.batch_alter_table('agency_cross_refs', schema=None) as batch_op:
        batch_op.drop_constraint('agency_cross_refs_pkey', type_='primary')
        batch_op.create_primary_key('agency_cross_refs_pkey', ['agency_id'])
        batch_op.create_foreign_key('agency_cross_refs_agency_id_fkey', 'agency', ['agency_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency_cross_refs', schema=None) as batch_op:
        batch_op.drop_constraint('agency_cross_refs_agency_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('agency_cross_refs_pkey', type_='primary')
        batch_op.create_primary_key('agency_cross_refs_pkey', ['agency_name'])
        batch_op.alter_column('agency_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
