"""add ff_application_id

Revision ID: b183aabe0707
Revises: 211a0fba4348
Create Date: 2025-04-02 13:18:17.058287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b183aabe0707'
down_revision = '211a0fba4348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ff_application_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('ff_application_id')

    # ### end Alembic commands ###
