"""empty message

Revision ID: b4b054d65515
Revises: 25ad6d340253
Create Date: 2023-12-02 10:14:10.698228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b054d65515'
down_revision = '25ad6d340253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impound_reason_codes',
    sa.Column('df_unique_code', sa.String(), nullable=False),
    sa.Column('impound_reason_name', sa.String(), nullable=True),
    sa.Column('vips_value_cd', sa.String(), nullable=True),
    sa.Column('vips_value_dsc', sa.String(), nullable=True),
    sa.Column('vips_value_abbreviated_dsc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('df_unique_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impound_reason_codes')
    # ### end Alembic commands ###
