"""charges_blood_test_flags

Revision ID: b5039cb318db
Revises: 6ff005a1c1e6
Create Date: 2026-02-12 14:13:42.654678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5039cb318db'
down_revision = '6ff005a1c1e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema='TAR') as batch_op:
        batch_op.add_column(sa.Column('has_charges', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('blood_alc_tests_taken', sa.String(length=1), nullable=True))

    op.execute("UPDATE \"TAR\".entity set has_charges = 'Y' where charges_blood_alc_tests_taken = 'Y'")
    op.execute("UPDATE \"TAR\".entity set blood_alc_tests_taken = 'Y' where charges_blood_alc_tests_taken = 'Y'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema='TAR') as batch_op:
        batch_op.drop_column('blood_alc_tests_taken')
        batch_op.drop_column('has_charges')

    # ### end Alembic commands ###
