"""df_error_submission_id

Revision ID: c15ff5018553
Revises: 4426dcf8e87c
Create Date: 2025-09-03 10:58:25.729315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15ff5018553'
down_revision = '4426dcf8e87c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('df_errors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'submission', ['submission_id'], ['submission_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('df_errors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('submission_id')

    # ### end Alembic commands ###
