"""refactor_agency

Revision ID: c33984651d3c
Revises: 739e768fe927
Create Date: 2025-08-01 15:26:08.412963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33984651d3c'
down_revision = '739e768fe927'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("update agency_cross_refs acr set agency_id = null;")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency_cross_refs', schema=None) as batch_op:
        batch_op.alter_column('agency_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='agency_id::integer')
    op.execute(
        """
        update agency_cross_refs acr set agency_id = (select id from agency a where a.agency_name = acr.agency_name);
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency_cross_refs', schema=None) as batch_op:
        batch_op.alter_column('agency_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        
    op.execute("update agency_cross_refs acr set agency_id = acr.prime_vjur;")

    # ### end Alembic commands ###
