"""add_agency_admin

Revision ID: cd52617ca649
Revises: a1b2c3d4e5f6
Create Date: 2026-06-08 16:25:31.257650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd52617ca649'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_dt', sa.DateTime(), nullable=False),
    sa.Column('updated_dt', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_guid'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.user_guid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agency_admin')
    # ### end Alembic commands ###
