"""update_involved_person_required

Revision ID: d8a9807b33a8
Revises: 8da833e0d308
Create Date: 2026-02-26 13:48:10.191784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a9807b33a8'
down_revision = '8da833e0d308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('involved_person', schema='TAR') as batch_op:
        batch_op.alter_column('position_of_person',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('safety_equipment_used',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('ejection_from_vehicle',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('severe_injury_location',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('injury_type',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('involved_person', schema='TAR') as batch_op:
        batch_op.alter_column('injury_type',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('severe_injury_location',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('ejection_from_vehicle',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('safety_equipment_used',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('position_of_person',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)

    # ### end Alembic commands ###
