"""empty message

Revision ID: dc0599cd958e
Revises: f76bbde02978
Create Date: 2023-11-23 09:27:12.436877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0599cd958e'
down_revision = 'f76bbde02978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdiction_cross_ref',
    sa.Column('jurisdiction_name', sa.String(), nullable=False),
    sa.Column('jurisdiction_code', sa.String(), nullable=True),
    sa.Column('prime_jurisdiction_code', sa.String(), nullable=True),
    sa.Column('icbc_jurisdiction_code', sa.String(), nullable=True),
    sa.Column('icbc_jurisdiction', sa.String(), nullable=True),
    sa.Column('vips_jurisdictions_objectCd', sa.String(), nullable=True),
    sa.Column('vips_jurisdictions_objectDsc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('jurisdiction_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jurisdiction_cross_ref')
    # ### end Alembic commands ###
