"""add_mv6020_officer_email

Revision ID: e19fe700a553
Revises: a3ea854753c0
Create Date: 2026-03-26 14:38:50.608318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19fe700a553'
down_revision = 'a3ea854753c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional_collision_details', schema='TAR') as batch_op:
        batch_op.add_column(sa.Column('officer_email', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional_collision_details', schema='TAR') as batch_op:
        batch_op.drop_column('officer_email')

    # ### end Alembic commands ###
