"""update_involved_person

Revision ID: ef01a1713b87
Revises: 30c4471aa64b
Create Date: 2025-12-08 17:00:22.891184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef01a1713b87'
down_revision = '30c4471aa64b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('involved_person', schema='TAR') as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('involved_person', schema='TAR') as batch_op:
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
