"""add_user_applied_dt

Revision ID: f5b20654641d
Revises: 1329abd472f4
Create Date: 2026-10-05 15:32:07.809911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b20654641d'
down_revision = '1329abd472f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applied_dt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_dt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('approved_dt')
        batch_op.drop_column('applied_dt')

    # ### end Alembic commands ###
