"""add_basics_ASD_fields

Revision ID: f7da321cfe41
Revises: 6f736d2fcec2
Create Date: 2026-07-24 10:19:54.540194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7da321cfe41'
down_revision = '6f736d2fcec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('irp_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasonable_suspicion_formed', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))
        batch_op.add_column(sa.Column('mandatory_alcohol_screening_demand', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('irp_form', schema=None) as batch_op:
        batch_op.drop_column('mandatory_alcohol_screening_demand')
        batch_op.drop_column('reasonable_suspicion_formed')

    # ### end Alembic commands ###
