"""police_agency_update

Revision ID: fa35ba99f01b
Revises: 39620e94361d
Create Date: 2026-02-23 11:32:06.406850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa35ba99f01b'
down_revision = '39620e94361d'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TABLE \"TAR\".police_agency DISABLE TRIGGER ALL;")
    op.execute("ALTER TABLE \"TAR\".collision DISABLE TRIGGER ALL;")
    op.execute(
        """
update "TAR".police_agency set code='0216', district_id=2, agency_name = '100 MILE HOUSE', icbc_prefix ='R' where code='216';
update "TAR".police_agency set code='0408', district_id=5, agency_name = 'ABBOTSFORD (M)', icbc_prefix ='M' where code='408';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('0701', 5, 'ABBOTSFORD (R)', 'R');
update "TAR".police_agency set code='0703', district_id=3, agency_name = 'AGASSIZ', icbc_prefix ='R' where code='703';
update "TAR".police_agency set code='0901', district_id=4, agency_name = 'ALERT BAY', icbc_prefix ='R' where code='901';
update "TAR".police_agency set code='0201', district_id=2, agency_name = 'ALEXIS CREEK', icbc_prefix ='R' where code='201';
update "TAR".police_agency set code='0202', district_id=2, agency_name = 'ANAHIM LAKE', icbc_prefix ='R' where code='202';
update "TAR".police_agency set code='0101', district_id=1, agency_name = 'ARMSTRONG', icbc_prefix ='R' where code='101';
update "TAR".police_agency set code='0203', district_id=1, agency_name = 'ASHCROFT', icbc_prefix ='R' where code='203';
update "TAR".police_agency set code='0601', district_id=2, agency_name = 'ATLIN', icbc_prefix ='R' where code='601';
update "TAR".police_agency set code='0204', district_id=1, agency_name = 'BARRIERE', icbc_prefix ='R' where code='204';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('9002', 3, 'BCHP 2ND LIONS GATE BRIDGE', 'H');
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('9005', 3, 'BCHP 2ND MIDDLE ARM BRIDGE', 'H');
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('9001', 3, 'BCHP 2ND NARROWS BRIDGE', 'H');
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('9004', 3, 'BCHP 2ND OAK STREET BRIDGE', 'H');
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('9003', 3, 'BCHP 2ND PORT MANN BRIDGE', 'H');
update "TAR".police_agency set code='0620', district_id=2, agency_name = 'BELLA BELLA', icbc_prefix ='R' where code='620';
update "TAR".police_agency set code='0602', district_id=2, agency_name = 'BELLA COOLA', icbc_prefix ='R' where code='602';
update "TAR".police_agency set code='0705', district_id=3, agency_name = 'BOSTON BAR', icbc_prefix ='R' where code='705';
update "TAR".police_agency set code='0742', district_id=3, agency_name = 'BOWEN ISLAND', icbc_prefix ='R' where code='742';
update "TAR".police_agency set code='0704', district_id=3, agency_name = 'BURNABY', icbc_prefix ='R' where code='704';
update "TAR".police_agency set code='0501', district_id=2, agency_name = 'BURNS LAKE', icbc_prefix ='R' where code='501';
update "TAR".police_agency set code='1003', district_id=7, agency_name = 'C N POLICE', icbc_prefix ='R' where code='1003';
update "TAR".police_agency set code='1004', district_id=7, agency_name = 'C P POLICE', icbc_prefix ='R' where code='1004';
update "TAR".police_agency set code='0903', district_id=4, agency_name = 'CAMPBELL RIVER (M)', icbc_prefix ='R' where code='903';
update "TAR".police_agency set code='0902', district_id=4, agency_name = 'CAMPBELL RIVER (R)', icbc_prefix ='R' where code='902';
update "TAR".police_agency set code='0301', district_id=1, agency_name = 'CASTLEGAR', icbc_prefix ='R' where code='327';
update "TAR".police_agency set code='0327', district_id=1, agency_name = 'CASTLEGAR', icbc_prefix ='R' where code='301';
update "TAR".police_agency set code='0404', district_id=5, agency_name = 'CENTRAL SAANICH', icbc_prefix ='C' where code='404';
update "TAR".police_agency set code='0206', district_id=1, agency_name = 'CHASE', icbc_prefix ='R' where code='206';
update "TAR".police_agency set code='0502', district_id=2, agency_name = 'CHETWYND', icbc_prefix ='R' where code='502';
update "TAR".police_agency set code='0707', district_id=3, agency_name = 'CHILLIWACK (M)', icbc_prefix ='R' where code='707';
update "TAR".police_agency set code='0706', district_id=3, agency_name = 'CHILLIWACK (R)', icbc_prefix ='R' where code='706';
update "TAR".police_agency set code='0207', district_id=1, agency_name = 'CLEARWATER', icbc_prefix ='R' where code='207';
update "TAR".police_agency set code='0208', district_id=1, agency_name = 'CLINTON', icbc_prefix ='R' where code='208';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('1005', 7, 'CNR POLICE VANCOUVER', 'R');
update "TAR".police_agency set code='0125', district_id=1, agency_name = 'COLDSTREAM', icbc_prefix ='R' where code='125';
update "TAR".police_agency set code='0311', district_id=1, agency_name = 'INVERMERE', icbc_prefix ='R' where code='311';
update "TAR".police_agency set code='0821', district_id=4, agency_name = 'WEST SHORE/COLWOOD', icbc_prefix ='R' where code='821';
update "TAR".police_agency set code='0904', district_id=4, agency_name = 'COMOX', icbc_prefix ='R' where code='904';
update "TAR".police_agency set code='0905', district_id=4, agency_name = 'COURTENAY (R)', icbc_prefix ='R' where code='905';
update "TAR".police_agency set code='0710', district_id=3, agency_name = 'COQUITLAM (M)', icbc_prefix ='R' where code='710';
update "TAR".police_agency set code='0709', district_id=3, agency_name = 'COQUITLAM (P)', icbc_prefix ='R' where code='709';
update "TAR".police_agency set code='0906', district_id=4, agency_name = 'COURTENAY (M)', icbc_prefix ='R' where code='906';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('1006', 7, 'CPR POLICE VANCOUVER', 'R');
update "TAR".police_agency set code='0303', district_id=1, agency_name = 'CRANBROOK (M)', icbc_prefix ='R' where code='303';
update "TAR".police_agency set code='0302', district_id=1, agency_name = 'CRANBROOK (R)', icbc_prefix ='R' where code='302';
update "TAR".police_agency set code='0305', district_id=1, agency_name = 'CRESTON', icbc_prefix ='R' where code='305';
update "TAR".police_agency set code='0504', district_id=2, agency_name = 'DAWSON CREEK (M)', icbc_prefix ='R' where code='504';
update "TAR".police_agency set code='0503', district_id=2, agency_name = 'DAWSON CREEK (R)', icbc_prefix ='R' where code='503';
update "TAR".police_agency set code='0615', district_id=2, agency_name = 'DEASE LAKE', icbc_prefix ='R' where code='615';
update "TAR".police_agency set code='0407', district_id=5, agency_name = 'DELTA', icbc_prefix ='D' where code='407';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('9010', 4, 'DEPARTURE BAY TERMINAL', 'R');
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('1104', 4, 'DITIDAHT FIRST NATION POLICE', 'R');
update "TAR".police_agency set code='0804', district_id=4, agency_name = 'DUNCAN (M)', icbc_prefix ='R' where code='804';
update "TAR".police_agency set code='0803', district_id=4, agency_name = 'DUNCAN (R)', icbc_prefix ='R' where code='803';
update "TAR".police_agency set code='0329', district_id=1, agency_name = 'ELKFORD', icbc_prefix ='R' where code='329';
update "TAR".police_agency set code='0102', district_id=1, agency_name = 'ENDERBY', icbc_prefix ='R' where code='102';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('0405', 5, 'ESQUIMALT', 'E');
update "TAR".police_agency set code='0103', district_id=1, agency_name = 'FALKLAND', icbc_prefix ='R' where code='103';
update "TAR".police_agency set code='0306', district_id=1, agency_name = 'FERNIE', icbc_prefix ='R' where code='306';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('0307', 1, 'FIELD', 'R');
update "TAR".police_agency set code='0505', district_id=2, agency_name = 'FORT NELSON', icbc_prefix ='R' where code='505';
update "TAR".police_agency set code='0506', district_id=2, agency_name = 'FORT ST. JAMES', icbc_prefix ='R' where code='506';
update "TAR".police_agency set code='0508', district_id=2, agency_name = 'FORT ST. JOHN (M)', icbc_prefix ='R' where code='508';
update "TAR".police_agency set code='0507', district_id=2, agency_name = 'FORT ST. JOHN (R)', icbc_prefix ='R' where code='507';
update "TAR".police_agency set code='0509', district_id=2, agency_name = 'FRASER LAKE', icbc_prefix ='R' where code='509';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('0308', 1, 'FRUITVALE', 'R');
update "TAR".police_agency set code='0805', district_id=4, agency_name = 'GABRIOLA ISLAND', icbc_prefix ='R' where code='805';
update "TAR".police_agency set code='0806', district_id=4, agency_name = 'GANGES/SALTSPRING ISLAND', icbc_prefix ='R' where code='806';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('9006', 3, 'GEORGE MASSEY TUNNEL', 'R');
update "TAR".police_agency set code='0715', district_id=3, agency_name = 'GIBSONS', icbc_prefix ='R' where code='715';
update "TAR".police_agency set code='0907', district_id=4, agency_name = 'GOLD RIVER', icbc_prefix ='R' where code='907';
update "TAR".police_agency set code='0309', district_id=1, agency_name = 'GOLDEN/FIELD', icbc_prefix ='R' where code='309';
update "TAR".police_agency set code='0310', district_id=1, agency_name = 'GRAND FORKS', icbc_prefix ='R' where code='310';
update "TAR".police_agency set code='0619', district_id=2, agency_name = 'GRANISLE', icbc_prefix ='R' where code='619';
update "TAR".police_agency set code='0811', district_id=4, agency_name = 'GULF ISLANDS/PENDER ISLAND', icbc_prefix ='R' where code='811';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('0734', 7, 'HIGHWAY PATROL', 'R');
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('0735', 7, 'HIGHWAY PATROL', 'R');
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('0736', 7, 'HIGHWAY PATROL (ABBOTSFORD)', 'R');
update "TAR".police_agency set code='0714', district_id=3, agency_name = 'HOPE', icbc_prefix ='R' where code='714';
update "TAR".police_agency set code='0745', district_id=3, agency_name = 'HOPE', icbc_prefix ='R' where code='745';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('9009', 3, 'HORSESHOE BAY TERMINAL', 'R');
update "TAR".police_agency set code='0605', district_id=2, agency_name = 'HOUSTON', icbc_prefix ='R' where code='605';
update "TAR".police_agency set code='0510', district_id=2, agency_name = 'HUDSONS H', icbc_prefix ='R' where code='510';
update "TAR".police_agency set code='0210', district_id=1, agency_name = 'KAMLOOPS (M)', icbc_prefix ='R' where code='210';
update "TAR".police_agency set code='0209', district_id=1, agency_name = 'KAMLOOPS (R)', icbc_prefix ='R' where code='209';
update "TAR".police_agency set code='0312', district_id=1, agency_name = 'KASLO', icbc_prefix ='R' where code='312';
update "TAR".police_agency set code='0105', district_id=1, agency_name = 'KELOWNA (M)', icbc_prefix ='R' where code='105';
update "TAR".police_agency set code='0104', district_id=1, agency_name = 'KELOWNA (R)', icbc_prefix ='R' where code='104';
update "TAR".police_agency set code='0106', district_id=1, agency_name = 'KEREMEOS', icbc_prefix ='R' where code='106';
update "TAR".police_agency set code='0314', district_id=1, agency_name = 'KIMBERLEY (M)', icbc_prefix ='R' where code='314';
update "TAR".police_agency set code='0313', district_id=1, agency_name = 'KIMBERLEY (R)', icbc_prefix ='R' where code='313';
update "TAR".police_agency set code='1103', district_id=6, agency_name = 'KITASOO/XAIXAIS TRIBAL POLICE', icbc_prefix ='R' where code='1103';
update "TAR".police_agency set code='0607', district_id=2, agency_name = 'KITIMAT (M)', icbc_prefix ='R' where code='607';
update "TAR".police_agency set code='0606', district_id=2, agency_name = 'KITIMAT (R)', icbc_prefix ='R' where code='606';
update "TAR".police_agency set code='0824', district_id=4, agency_name = 'LADYSMITH', icbc_prefix ='R' where code='824';
update "TAR".police_agency set code='0807', district_id=4, agency_name = 'LADYSMITH', icbc_prefix ='R' where code='807';
update "TAR".police_agency set code='0127', district_id=1, agency_name = 'LAKE COUNTRY', icbc_prefix ='R' where code='127';
update "TAR".police_agency set code='0808', district_id=4, agency_name = 'LAKE COWICHAN', icbc_prefix ='R' where code='808';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('9011', 3, 'LANGDALE TERMINAL', 'R');
update "TAR".police_agency set code='0823', district_id=4, agency_name = 'LANGFORD', icbc_prefix ='R' where code='823';
update "TAR".police_agency set code='0716', district_id=3, agency_name = 'LANGLEY (C)', icbc_prefix ='R' where code='716';
update "TAR".police_agency set code='0717', district_id=3, agency_name = 'LANGLEY (D)', icbc_prefix ='R' where code='717';
update "TAR".police_agency set code='0211', district_id=1, agency_name = 'LILLOOET', icbc_prefix ='R' where code='211';
update "TAR".police_agency set code='0212', district_id=1, agency_name = 'LOGAN LAKE', icbc_prefix ='R' where code='212';
update "TAR".police_agency set code='0107', district_id=1, agency_name = 'LUMBY', icbc_prefix ='R' where code='107';
update "TAR".police_agency set code='0213', district_id=1, agency_name = 'LYTTON', icbc_prefix ='R' where code='213';
update "TAR".police_agency set code='0522', district_id=2, agency_name = 'MACKENZIE (M)', icbc_prefix ='R' where code='522';
update "TAR".police_agency set code='0511', district_id=2, agency_name = 'MACKENZIE (R)', icbc_prefix ='R' where code='511';
update "TAR".police_agency set code='0713', district_id=3, agency_name = 'MAPLE RIDGE', icbc_prefix ='R' where code='713';
update "TAR".police_agency set code='0608', district_id=2, agency_name = 'MASSET', icbc_prefix ='R' where code='608';
update "TAR".police_agency set code='0512', district_id=2, agency_name = 'MCBRIDE', icbc_prefix ='R' where code='512';
update "TAR".police_agency set code='0215', district_id=1, agency_name = 'MERRITT (M)', icbc_prefix ='R' where code='215';
update "TAR".police_agency set code='0214', district_id=1, agency_name = 'MERRITT (R)', icbc_prefix ='R' where code='214';
update "TAR".police_agency set code='0315', district_id=1, agency_name = 'MIDWAY', icbc_prefix ='R' where code='315';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('2001', 7, 'MILITARY POLICE', 'K');
update "TAR".police_agency set code='0719', district_id=3, agency_name = 'MISSION (M)', icbc_prefix ='R' where code='719';
update "TAR".police_agency set code='0718', district_id=3, agency_name = 'MISSION (R)', icbc_prefix ='R' where code='718';
update "TAR".police_agency set code='0316', district_id=1, agency_name = 'NAKUSP', icbc_prefix ='R' where code='316';
update "TAR".police_agency set code='0810', district_id=4, agency_name = 'NANAIMO (M)', icbc_prefix ='R' where code='810';
update "TAR".police_agency set code='0809', district_id=4, agency_name = 'NANAIMO (R)', icbc_prefix ='R' where code='809';
update "TAR".police_agency set code='0411', district_id=5, agency_name = 'NELSON - POLICE', icbc_prefix ='T' where code='411';
update "TAR".police_agency set code='0317', district_id=1, agency_name = 'NELSON - RCMP', icbc_prefix ='R' where code='317';
update "TAR".police_agency set code='0621', district_id=2, agency_name = 'NEW AIYANSH', icbc_prefix ='R' where code='621';
update "TAR".police_agency set code='0604', district_id=2, agency_name = 'NEW HAZELTON', icbc_prefix ='R' where code='604';
update "TAR".police_agency set code='0409', district_id=5, agency_name = 'NEW WESTMINSTER', icbc_prefix ='N' where code='409';
update "TAR".police_agency set code='0730', district_id=5, agency_name = 'SURREY - POLICE', icbc_prefix ='U' where code='730';
update "TAR".police_agency set code='0820', district_id=4, agency_name = 'NORTH SAANICH', icbc_prefix ='R' where code='820';
update "TAR".police_agency set code='0720', district_id=3, agency_name = 'NORTH VANCOUVER (C)', icbc_prefix ='R' where code='720';
update "TAR".police_agency set code='0721', district_id=3, agency_name = 'NORTH VANCOUVER (D)', icbc_prefix ='R' where code='721';
update "TAR".police_agency set code='0748', district_id=3, agency_name = 'NORTH VANCOUVER (P)', icbc_prefix ='R' where code='748';
update "TAR".police_agency set code='0406', district_id=5, agency_name = 'OAK BAY', icbc_prefix ='B' where code='406';
update "TAR".police_agency set code='0908', district_id=4, agency_name = 'PARKSVILLE/OCEANSIDE', icbc_prefix ='R' where code='908';
update "TAR".police_agency set code='0109', district_id=1, agency_name = 'OLIVER', icbc_prefix ='R' where code='109';
update "TAR".police_agency set code='0110', district_id=1, agency_name = 'OSOYOOS', icbc_prefix ='R' where code='110';
update "TAR".police_agency set code='0922', district_id=4, agency_name = 'PARKSVILLE/OCEANSIDE', icbc_prefix ='R' where code='922';
update "TAR".police_agency set code='0737', district_id=3, agency_name = 'PEMBERTON', icbc_prefix ='R' where code='737';
update "TAR".police_agency set code='0112', district_id=1, agency_name = 'PENTICTON (M)', icbc_prefix ='R' where code='112';
update "TAR".police_agency set code='0111', district_id=1, agency_name = 'PENTICTON (R)', icbc_prefix ='R' where code='111';
update "TAR".police_agency set code='0741', district_id=3, agency_name = 'PITT MEADOWS', icbc_prefix ='R' where code='741';
update "TAR".police_agency set code='0910', district_id=4, agency_name = 'PORT ALBERNI (M)', icbc_prefix ='R' where code='910';
update "TAR".police_agency set code='0909', district_id=4, agency_name = 'PORT ALBERNI (R)', icbc_prefix ='R' where code='909';
update "TAR".police_agency set code='0911', district_id=4, agency_name = 'PORT ALICE', icbc_prefix ='R' where code='911';
update "TAR".police_agency set code='0711', district_id=3, agency_name = 'PORT COQUITLAM', icbc_prefix ='R' where code='711';
update "TAR".police_agency set code='0912', district_id=4, agency_name = 'PORT HARDY', icbc_prefix ='R' where code='912';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('0923', 4, 'PORT HARDY', 'R');
update "TAR".police_agency set code='0913', district_id=4, agency_name = 'PORT MCNEILL', icbc_prefix ='R' where code='913';
update "TAR".police_agency set code='0412', district_id=5, agency_name = 'PORT MOODY', icbc_prefix ='P' where code='412';
update "TAR".police_agency set code='0915', district_id=4, agency_name = 'POWELL RIVER (M)', icbc_prefix ='R' where code='915';
update "TAR".police_agency set code='0914', district_id=4, agency_name = 'POWELL RIVER (R)', icbc_prefix ='R' where code='914';
update "TAR".police_agency set code='0521', district_id=2, agency_name = 'PRINCE GEORGE (M)', icbc_prefix ='R' where code='521';
update "TAR".police_agency set code='0513', district_id=2, agency_name = 'PRINCE GEORGE (R)', icbc_prefix ='R' where code='513';
update "TAR".police_agency set code='0611', district_id=2, agency_name = 'PRINCE RUPERT (M)', icbc_prefix ='R' where code='611';
update "TAR".police_agency set code='0610', district_id=2, agency_name = 'PRINCE RUPERT (R)', icbc_prefix ='R' where code='610';
update "TAR".police_agency set code='0113', district_id=1, agency_name = 'PRINCETON', icbc_prefix ='R' where code='113';
update "TAR".police_agency set code='0916', district_id=4, agency_name = 'QUADRA ISLAND', icbc_prefix ='R' where code='916';
update "TAR".police_agency set code='0925', district_id=4, agency_name = 'QUALICUM BEACH', icbc_prefix ='R' where code='925';
update "TAR".police_agency set code='0612', district_id=2, agency_name = 'QUEEN CHARLOTTE', icbc_prefix ='R' where code='612';
update "TAR".police_agency set code='0515', district_id=2, agency_name = 'QUESNEL (M)', icbc_prefix ='R' where code='515';
update "TAR".police_agency set code='0514', district_id=2, agency_name = 'QUESNEL (R)', icbc_prefix ='R' where code='514';
update "TAR".police_agency set code='0114', district_id=1, agency_name = 'REVELSTOKE', icbc_prefix ='R' where code='114';
update "TAR".police_agency set code='0124', district_id=1, agency_name = 'REVELSTOKE', icbc_prefix ='R' where code='124';
update "TAR".police_agency set code='0722', district_id=3, agency_name = 'RICHMOND', icbc_prefix ='R' where code='722';
update "TAR".police_agency set code='0712', district_id=3, agency_name = 'RIDGE MEADOWS', icbc_prefix ='R' where code='712';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('0320', 1, 'ROSSLAND', 'R');
update "TAR".police_agency set code='0403', district_id=5, agency_name = 'SAANICH', icbc_prefix ='S' where code='403';
update "TAR".police_agency set code='0321', district_id=1, agency_name = 'SALMO', icbc_prefix ='R' where code='321';
update "TAR".police_agency set code='0116', district_id=1, agency_name = 'SALMON ARM (M)', icbc_prefix ='R' where code='116';
update "TAR".police_agency set code='0115', district_id=1, agency_name = 'SALMON ARM (R)', icbc_prefix ='R' where code='115';
update "TAR".police_agency set code='0917', district_id=4, agency_name = 'SAYWARD', icbc_prefix ='R' where code='917';
update "TAR".police_agency set code='0723', district_id=3, agency_name = 'SECHELT', icbc_prefix ='R' where code='723';
update "TAR".police_agency set code='0743', district_id=3, agency_name = 'SECHELT', icbc_prefix ='R' where code='743';
update "TAR".police_agency set code='0812', district_id=4, agency_name = 'SHAWNIGAN LAKE', icbc_prefix ='R' where code='812';
update "TAR".police_agency set code='0117', district_id=1, agency_name = 'SICAMOUS', icbc_prefix ='R' where code='117';
update "TAR".police_agency set code='0814', district_id=4, agency_name = 'SIDNEY (M)', icbc_prefix ='R' where code='814';
update "TAR".police_agency set code='0813', district_id=4, agency_name = 'SIDNEY (R)', icbc_prefix ='R' where code='813';
update "TAR".police_agency set code='0318', district_id=1, agency_name = 'SLOCAN LAKE', icbc_prefix ='R' where code='318';
update "TAR".police_agency set code='0613', district_id=2, agency_name = 'SMITHERS', icbc_prefix ='R' where code='613';
update "TAR".police_agency set code='0622', district_id=2, agency_name = 'SMITHERS', icbc_prefix ='R' where code='622';
update "TAR".police_agency set code='0815', district_id=4, agency_name = 'SOOKE', icbc_prefix ='R' where code='815';
update "TAR".police_agency set code='0827', district_id=4, agency_name = 'SOOKE (M)', icbc_prefix ='R' where code='827';
update "TAR".police_agency set code='0126', district_id=1, agency_name = 'SPALLUMCHEEN', icbc_prefix ='R' where code='126';
update "TAR".police_agency set code='0322', district_id=1, agency_name = 'SPARWOOD', icbc_prefix ='R' where code='322';
update "TAR".police_agency set code='0725', district_id=3, agency_name = 'SQUAMISH (M)', icbc_prefix ='R' where code='725';
update "TAR".police_agency set code='0724', district_id=3, agency_name = 'SQUAMISH (R)', icbc_prefix ='R' where code='724';
update "TAR".police_agency set code='0614', district_id=2, agency_name = 'STEWART', icbc_prefix ='R' where code='614';
update "TAR".police_agency set code='1101', district_id=6, agency_name = 'STL’ATL’IMX TRIBAL POLICE', icbc_prefix ='R' where code='1101';
update "TAR".police_agency set code='0121', district_id=1, agency_name = 'SUMMERLAND', icbc_prefix ='R' where code='121';
update "TAR".police_agency set code='0726', district_id=3, agency_name = 'SURREY', icbc_prefix ='R' where code='726';
update "TAR".police_agency set code='0739', district_id=3, agency_name = 'SURREY', icbc_prefix ='R' where code='739';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('9008', 4, 'SWARTZ BAY TERMINAL', 'R');
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('0918', 4, 'TAHSIS', 'R');
update "TAR".police_agency set code='0526', district_id=2, agency_name = 'TAKLA LANDING', icbc_prefix ='R' where code='526';
update "TAR".police_agency set code='0617', district_id=2, agency_name = 'TERRACE (M)', icbc_prefix ='R' where code='617';
update "TAR".police_agency set code='0616', district_id=2, agency_name = 'TERRACE (R)', icbc_prefix ='R' where code='616';
update "TAR".police_agency set code='0924', district_id=4, agency_name = 'TEXADA ISLAND', icbc_prefix ='R' where code='924';
update "TAR".police_agency set code='0919', district_id=4, agency_name = 'TOFINO', icbc_prefix ='R' where code='919';
update "TAR".police_agency set code='0324', district_id=1, agency_name = 'TRAIL (M)', icbc_prefix ='R' where code='324';
update "TAR".police_agency set code='0323', district_id=1, agency_name = 'TRAIL (R)', icbc_prefix ='R' where code='323';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('9007', 3, 'TSAWASSEN TERMINAL', 'R');
update "TAR".police_agency set code='0525', district_id=2, agency_name = 'TSAY KEH DENE', icbc_prefix ='R' where code='525';
update "TAR".police_agency set code='0524', district_id=2, agency_name = 'TUMBLER RIDGE', icbc_prefix ='R' where code='524';
update "TAR".police_agency set code='0920', district_id=4, agency_name = 'UCLUELET', icbc_prefix ='R' where code='920';
update "TAR".police_agency set code='0727', district_id=3, agency_name = 'UNIVERSITY', icbc_prefix ='R' where code='727';
update "TAR".police_agency set code='0218', district_id=2, agency_name = 'VALEMOUNT', icbc_prefix ='R' where code='218';
update "TAR".police_agency set code='0401', district_id=5, agency_name = 'VANCOUVER', icbc_prefix ='A' where code='401';
update "TAR".police_agency set code='0517', district_id=2, agency_name = 'VANDERHOOF', icbc_prefix ='R' where code='517';
update "TAR".police_agency set code='0119', district_id=1, agency_name = 'VERNON (M)', icbc_prefix ='R' where code='119';
update "TAR".police_agency set code='0118', district_id=1, agency_name = 'VERNON (R)', icbc_prefix ='R' where code='118';
update "TAR".police_agency set code='0402', district_id=5, agency_name = 'VICTORIA', icbc_prefix ='V' where code='402';
update "TAR".police_agency set code='0822', district_id=4, agency_name = 'VIEW ROYAL', icbc_prefix ='R' where code='822';
insert into "TAR".police_agency (code, district_id, agency_name, icbc_prefix) values ('0519', 2, 'WATSON LAKE', 'R');
update "TAR".police_agency set code='0518', district_id=2, agency_name = 'WELLS', icbc_prefix ='R' where code='518';
update "TAR".police_agency set code='0802', district_id=4, agency_name = 'WEST SHORE (P)', icbc_prefix ='R' where code='802';
update "TAR".police_agency set code='0410', district_id=5, agency_name = 'WEST VANCOUVER', icbc_prefix ='W' where code='410';
update "TAR".police_agency set code='0738', district_id=3, agency_name = 'WHISTLER', icbc_prefix ='R' where code='738';
update "TAR".police_agency set code='0747', district_id=3, agency_name = 'WHISTLER', icbc_prefix ='R' where code='747';
update "TAR".police_agency set code='0729', district_id=3, agency_name = 'WHITE ROCK', icbc_prefix ='R' where code='729';
update "TAR".police_agency set code='0221', district_id=2, agency_name = 'WILLIAMS LAKE (M)', icbc_prefix ='R' where code='221';
update "TAR".police_agency set code='0219', district_id=2, agency_name = 'WILLIAMS LAKE (R)', icbc_prefix ='R' where code='219';
        """
    )

    op.execute(
        """
update "TAR".collision set police_agency_code = '0216' where police_agency_code = '216';
update "TAR".collision set police_agency_code = '0408' where police_agency_code = '408';
update "TAR".collision set police_agency_code = '0703' where police_agency_code = '703';
update "TAR".collision set police_agency_code = '0901' where police_agency_code = '901';
update "TAR".collision set police_agency_code = '0201' where police_agency_code = '201';
update "TAR".collision set police_agency_code = '0202' where police_agency_code = '202';
update "TAR".collision set police_agency_code = '0101' where police_agency_code = '101';
update "TAR".collision set police_agency_code = '0203' where police_agency_code = '203';
update "TAR".collision set police_agency_code = '0601' where police_agency_code = '601';
update "TAR".collision set police_agency_code = '0204' where police_agency_code = '204';
update "TAR".collision set police_agency_code = '0620' where police_agency_code = '620';
update "TAR".collision set police_agency_code = '0602' where police_agency_code = '602';
update "TAR".collision set police_agency_code = '0705' where police_agency_code = '705';
update "TAR".collision set police_agency_code = '0742' where police_agency_code = '742';
update "TAR".collision set police_agency_code = '0704' where police_agency_code = '704';
update "TAR".collision set police_agency_code = '0501' where police_agency_code = '501';
update "TAR".collision set police_agency_code = '1003' where police_agency_code = '1003';
update "TAR".collision set police_agency_code = '1004' where police_agency_code = '1004';
update "TAR".collision set police_agency_code = '0903' where police_agency_code = '903';
update "TAR".collision set police_agency_code = '0902' where police_agency_code = '902';
update "TAR".collision set police_agency_code = '0301' where police_agency_code = '327';
update "TAR".collision set police_agency_code = '0327' where police_agency_code = '301';
update "TAR".collision set police_agency_code = '0404' where police_agency_code = '404';
update "TAR".collision set police_agency_code = '0206' where police_agency_code = '206';
update "TAR".collision set police_agency_code = '0502' where police_agency_code = '502';
update "TAR".collision set police_agency_code = '0707' where police_agency_code = '707';
update "TAR".collision set police_agency_code = '0706' where police_agency_code = '706';
update "TAR".collision set police_agency_code = '0207' where police_agency_code = '207';
update "TAR".collision set police_agency_code = '0208' where police_agency_code = '208';
update "TAR".collision set police_agency_code = '0125' where police_agency_code = '125';
update "TAR".collision set police_agency_code = '0311' where police_agency_code = '311';
update "TAR".collision set police_agency_code = '0821' where police_agency_code = '821';
update "TAR".collision set police_agency_code = '0904' where police_agency_code = '904';
update "TAR".collision set police_agency_code = '0905' where police_agency_code = '905';
update "TAR".collision set police_agency_code = '0710' where police_agency_code = '710';
update "TAR".collision set police_agency_code = '0709' where police_agency_code = '709';
update "TAR".collision set police_agency_code = '0906' where police_agency_code = '906';
update "TAR".collision set police_agency_code = '0303' where police_agency_code = '303';
update "TAR".collision set police_agency_code = '0302' where police_agency_code = '302';
update "TAR".collision set police_agency_code = '0305' where police_agency_code = '305';
update "TAR".collision set police_agency_code = '0504' where police_agency_code = '504';
update "TAR".collision set police_agency_code = '0503' where police_agency_code = '503';
update "TAR".collision set police_agency_code = '0615' where police_agency_code = '615';
update "TAR".collision set police_agency_code = '0407' where police_agency_code = '407';
update "TAR".collision set police_agency_code = '0804' where police_agency_code = '804';
update "TAR".collision set police_agency_code = '0803' where police_agency_code = '803';
update "TAR".collision set police_agency_code = '0329' where police_agency_code = '329';
update "TAR".collision set police_agency_code = '0102' where police_agency_code = '102';
update "TAR".collision set police_agency_code = '0103' where police_agency_code = '103';
update "TAR".collision set police_agency_code = '0306' where police_agency_code = '306';
update "TAR".collision set police_agency_code = '0505' where police_agency_code = '505';
update "TAR".collision set police_agency_code = '0506' where police_agency_code = '506';
update "TAR".collision set police_agency_code = '0508' where police_agency_code = '508';
update "TAR".collision set police_agency_code = '0507' where police_agency_code = '507';
update "TAR".collision set police_agency_code = '0509' where police_agency_code = '509';
update "TAR".collision set police_agency_code = '0805' where police_agency_code = '805';
update "TAR".collision set police_agency_code = '0806' where police_agency_code = '806';
update "TAR".collision set police_agency_code = '0715' where police_agency_code = '715';
update "TAR".collision set police_agency_code = '0907' where police_agency_code = '907';
update "TAR".collision set police_agency_code = '0309' where police_agency_code = '309';
update "TAR".collision set police_agency_code = '0310' where police_agency_code = '310';
update "TAR".collision set police_agency_code = '0619' where police_agency_code = '619';
update "TAR".collision set police_agency_code = '0811' where police_agency_code = '811';
update "TAR".collision set police_agency_code = '0714' where police_agency_code = '714';
update "TAR".collision set police_agency_code = '0745' where police_agency_code = '745';
update "TAR".collision set police_agency_code = '0605' where police_agency_code = '605';
update "TAR".collision set police_agency_code = '0510' where police_agency_code = '510';
update "TAR".collision set police_agency_code = '0210' where police_agency_code = '210';
update "TAR".collision set police_agency_code = '0209' where police_agency_code = '209';
update "TAR".collision set police_agency_code = '0312' where police_agency_code = '312';
update "TAR".collision set police_agency_code = '0105' where police_agency_code = '105';
update "TAR".collision set police_agency_code = '0104' where police_agency_code = '104';
update "TAR".collision set police_agency_code = '0106' where police_agency_code = '106';
update "TAR".collision set police_agency_code = '0314' where police_agency_code = '314';
update "TAR".collision set police_agency_code = '0313' where police_agency_code = '313';
update "TAR".collision set police_agency_code = '1103' where police_agency_code = '1103';
update "TAR".collision set police_agency_code = '0607' where police_agency_code = '607';
update "TAR".collision set police_agency_code = '0606' where police_agency_code = '606';
update "TAR".collision set police_agency_code = '0824' where police_agency_code = '824';
update "TAR".collision set police_agency_code = '0807' where police_agency_code = '807';
update "TAR".collision set police_agency_code = '0127' where police_agency_code = '127';
update "TAR".collision set police_agency_code = '0808' where police_agency_code = '808';
update "TAR".collision set police_agency_code = '0823' where police_agency_code = '823';
update "TAR".collision set police_agency_code = '0716' where police_agency_code = '716';
update "TAR".collision set police_agency_code = '0717' where police_agency_code = '717';
update "TAR".collision set police_agency_code = '0211' where police_agency_code = '211';
update "TAR".collision set police_agency_code = '0212' where police_agency_code = '212';
update "TAR".collision set police_agency_code = '0107' where police_agency_code = '107';
update "TAR".collision set police_agency_code = '0213' where police_agency_code = '213';
update "TAR".collision set police_agency_code = '0522' where police_agency_code = '522';
update "TAR".collision set police_agency_code = '0511' where police_agency_code = '511';
update "TAR".collision set police_agency_code = '0713' where police_agency_code = '713';
update "TAR".collision set police_agency_code = '0608' where police_agency_code = '608';
update "TAR".collision set police_agency_code = '0512' where police_agency_code = '512';
update "TAR".collision set police_agency_code = '0215' where police_agency_code = '215';
update "TAR".collision set police_agency_code = '0214' where police_agency_code = '214';
update "TAR".collision set police_agency_code = '0315' where police_agency_code = '315';
update "TAR".collision set police_agency_code = '0719' where police_agency_code = '719';
update "TAR".collision set police_agency_code = '0718' where police_agency_code = '718';
update "TAR".collision set police_agency_code = '0316' where police_agency_code = '316';
update "TAR".collision set police_agency_code = '0810' where police_agency_code = '810';
update "TAR".collision set police_agency_code = '0809' where police_agency_code = '809';
update "TAR".collision set police_agency_code = '0411' where police_agency_code = '411';
update "TAR".collision set police_agency_code = '0317' where police_agency_code = '317';
update "TAR".collision set police_agency_code = '0621' where police_agency_code = '621';
update "TAR".collision set police_agency_code = '0604' where police_agency_code = '604';
update "TAR".collision set police_agency_code = '0409' where police_agency_code = '409';
update "TAR".collision set police_agency_code = '0730' where police_agency_code = '730';
update "TAR".collision set police_agency_code = '0820' where police_agency_code = '820';
update "TAR".collision set police_agency_code = '0720' where police_agency_code = '720';
update "TAR".collision set police_agency_code = '0721' where police_agency_code = '721';
update "TAR".collision set police_agency_code = '0748' where police_agency_code = '748';
update "TAR".collision set police_agency_code = '0406' where police_agency_code = '406';
update "TAR".collision set police_agency_code = '0908' where police_agency_code = '908';
update "TAR".collision set police_agency_code = '0109' where police_agency_code = '109';
update "TAR".collision set police_agency_code = '0110' where police_agency_code = '110';
update "TAR".collision set police_agency_code = '0922' where police_agency_code = '922';
update "TAR".collision set police_agency_code = '0737' where police_agency_code = '737';
update "TAR".collision set police_agency_code = '0112' where police_agency_code = '112';
update "TAR".collision set police_agency_code = '0111' where police_agency_code = '111';
update "TAR".collision set police_agency_code = '0741' where police_agency_code = '741';
update "TAR".collision set police_agency_code = '0910' where police_agency_code = '910';
update "TAR".collision set police_agency_code = '0909' where police_agency_code = '909';
update "TAR".collision set police_agency_code = '0911' where police_agency_code = '911';
update "TAR".collision set police_agency_code = '0711' where police_agency_code = '711';
update "TAR".collision set police_agency_code = '0912' where police_agency_code = '912';
update "TAR".collision set police_agency_code = '0913' where police_agency_code = '913';
update "TAR".collision set police_agency_code = '0412' where police_agency_code = '412';
update "TAR".collision set police_agency_code = '0915' where police_agency_code = '915';
update "TAR".collision set police_agency_code = '0914' where police_agency_code = '914';
update "TAR".collision set police_agency_code = '0521' where police_agency_code = '521';
update "TAR".collision set police_agency_code = '0513' where police_agency_code = '513';
update "TAR".collision set police_agency_code = '0611' where police_agency_code = '611';
update "TAR".collision set police_agency_code = '0610' where police_agency_code = '610';
update "TAR".collision set police_agency_code = '0113' where police_agency_code = '113';
update "TAR".collision set police_agency_code = '0916' where police_agency_code = '916';
update "TAR".collision set police_agency_code = '0925' where police_agency_code = '925';
update "TAR".collision set police_agency_code = '0612' where police_agency_code = '612';
update "TAR".collision set police_agency_code = '0515' where police_agency_code = '515';
update "TAR".collision set police_agency_code = '0514' where police_agency_code = '514';
update "TAR".collision set police_agency_code = '0114' where police_agency_code = '114';
update "TAR".collision set police_agency_code = '0124' where police_agency_code = '124';
update "TAR".collision set police_agency_code = '0722' where police_agency_code = '722';
update "TAR".collision set police_agency_code = '0712' where police_agency_code = '712';
update "TAR".collision set police_agency_code = '0403' where police_agency_code = '403';
update "TAR".collision set police_agency_code = '0321' where police_agency_code = '321';
update "TAR".collision set police_agency_code = '0116' where police_agency_code = '116';
update "TAR".collision set police_agency_code = '0115' where police_agency_code = '115';
update "TAR".collision set police_agency_code = '0917' where police_agency_code = '917';
update "TAR".collision set police_agency_code = '0723' where police_agency_code = '723';
update "TAR".collision set police_agency_code = '0743' where police_agency_code = '743';
update "TAR".collision set police_agency_code = '0812' where police_agency_code = '812';
update "TAR".collision set police_agency_code = '0117' where police_agency_code = '117';
update "TAR".collision set police_agency_code = '0814' where police_agency_code = '814';
update "TAR".collision set police_agency_code = '0813' where police_agency_code = '813';
update "TAR".collision set police_agency_code = '0318' where police_agency_code = '318';
update "TAR".collision set police_agency_code = '0613' where police_agency_code = '613';
update "TAR".collision set police_agency_code = '0622' where police_agency_code = '622';
update "TAR".collision set police_agency_code = '0815' where police_agency_code = '815';
update "TAR".collision set police_agency_code = '0827' where police_agency_code = '827';
update "TAR".collision set police_agency_code = '0126' where police_agency_code = '126';
update "TAR".collision set police_agency_code = '0322' where police_agency_code = '322';
update "TAR".collision set police_agency_code = '0725' where police_agency_code = '725';
update "TAR".collision set police_agency_code = '0724' where police_agency_code = '724';
update "TAR".collision set police_agency_code = '0614' where police_agency_code = '614';
update "TAR".collision set police_agency_code = '1101' where police_agency_code = '1101';
update "TAR".collision set police_agency_code = '0121' where police_agency_code = '121';
update "TAR".collision set police_agency_code = '0726' where police_agency_code = '726';
update "TAR".collision set police_agency_code = '0739' where police_agency_code = '739';
update "TAR".collision set police_agency_code = '0526' where police_agency_code = '526';
update "TAR".collision set police_agency_code = '0617' where police_agency_code = '617';
update "TAR".collision set police_agency_code = '0616' where police_agency_code = '616';
update "TAR".collision set police_agency_code = '0924' where police_agency_code = '924';
update "TAR".collision set police_agency_code = '0919' where police_agency_code = '919';
update "TAR".collision set police_agency_code = '0324' where police_agency_code = '324';
update "TAR".collision set police_agency_code = '0323' where police_agency_code = '323';
update "TAR".collision set police_agency_code = '0525' where police_agency_code = '525';
update "TAR".collision set police_agency_code = '0524' where police_agency_code = '524';
update "TAR".collision set police_agency_code = '0920' where police_agency_code = '920';
update "TAR".collision set police_agency_code = '0727' where police_agency_code = '727';
update "TAR".collision set police_agency_code = '0218' where police_agency_code = '218';
update "TAR".collision set police_agency_code = '0401' where police_agency_code = '401';
update "TAR".collision set police_agency_code = '0517' where police_agency_code = '517';
update "TAR".collision set police_agency_code = '0119' where police_agency_code = '119';
update "TAR".collision set police_agency_code = '0118' where police_agency_code = '118';
update "TAR".collision set police_agency_code = '0402' where police_agency_code = '402';
update "TAR".collision set police_agency_code = '0822' where police_agency_code = '822';
update "TAR".collision set police_agency_code = '0518' where police_agency_code = '518';
update "TAR".collision set police_agency_code = '0802' where police_agency_code = '802';
update "TAR".collision set police_agency_code = '0410' where police_agency_code = '410';
update "TAR".collision set police_agency_code = '0738' where police_agency_code = '738';
update "TAR".collision set police_agency_code = '0747' where police_agency_code = '747';
update "TAR".collision set police_agency_code = '0729' where police_agency_code = '729';
update "TAR".collision set police_agency_code = '0221' where police_agency_code = '221';
update "TAR".collision set police_agency_code = '0219' where police_agency_code = '219';
        """)

    op.execute("ALTER TABLE \"TAR\".police_agency ENABLE TRIGGER ALL;")
    op.execute("ALTER TABLE \"TAR\".collision ENABLE TRIGGER ALL;")


def downgrade():
    pass
