# FROM python:3.7.3-stretch
# FROM python:3.9-slim
FROM artifacts.developer.gov.bc.ca/dbe7-images/rhel8-python39:1-196.1725368453

COPY form_handler/requirements.txt /tmp/

RUN pip install --upgrade pip
RUN pip install -r /tmp/requirements.txt

WORKDIR /app
ENV PYTHONPATH /app/

COPY common /app/python/common
COPY form_handler /app/python/form_handler
COPY prohibition_web_svc/models.py /app/python/form_handler/models.py

# RUN ["python", "-m", "pytest"]

CMD [ "python", "./python/form_handler/listener.py" ]
