# FROM python:3.7.3-stretch
FROM python:3.9-slim

COPY form_handler/requirements.txt /tmp/

RUN pip install --upgrade pip
RUN pip install -r /tmp/requirements.txt

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

ENV PYTHONPATH /home/appuser/

COPY common /home/appuser/python/common
COPY form_handler /home/appuser/python/form_handler
COPY prohibition_web_svc/models.py /home/appuser/python/form_handler/models.py

# RUN ["python", "-m", "pytest"]

CMD [ "python", "./python/form_handler/listener.py" ]
