from .base import db,migrate

from .form import Form
from .user import User
from .user_role import UserRole
from .agency import Agency
from .city import City
from .country import Country
from .impound_lot_operator import ImpoundLotOperator
from .jurisdiction import Jurisdiction
from .jurisdiction_country import JurisdictionCountry
from .nsc_puj import NSCPuj
from .permission import Permission
from .province import Province
from .vehicle_style import VehicleStyle
from .vehicle_type import VehicleType
from .vehicle import Vehicle
from .vehicle_colour import VehicleColour
from .event import Event
from .twenty_four_hour_form import TwentyFourHourForm
from .twelve_hour_form import TwelveHourForm
from .irp_form import IRPForm
from .vi_form import VIForm
from .form_storage_refs import FormStorageRefs
from .agency_crossref import AgencyCrossref
from .jurisdiction_crossref import JurisdictionCrossRef
from .city_crossref import CityCrossRef
from .impound_reason_codes import ImpoundReasonCodes
from .ilo_id_crossref import IloIdCrossRef
from .df_errors import DFErrors
from .submission import Submission
from .submission_form_refs import SubmissionFormRef
from .submission_event import SubmissionEvent
from .TAR.collision import TarCollision
from .TAR.additional_collision_details import TarAdditionalCollisionDetails
from .TAR.location import TarLocation
from .TAR.witness_info import TarWitnessInfo
from .TAR.entity import TarEntity
from .TAR.involved_person import TarInvolvedPerson
from .TAR.charges import TarCharges
from .TAR.road_class import TarRoadClass
from .TAR.traffic_flow import TarTrafficFlow
from .TAR.collision_location import TarCollisionLocation
from .TAR.collision_scenario import TarCollisionScenario
from .TAR.speed_zone import TarSpeedZone
from .TAR.land_usage import TarLandUsage
from .TAR.road_type import TarRoadType
from .TAR.traffic_control import TarTrafficControl
from .TAR.roadway_character import TarRoadwayCharacter
from .TAR.roadway_condition import TarRoadwayCondition
from .TAR.weather_condition import TarWeatherCondition
from .TAR.lighting_condition import TarLightingCondition
from .TAR.type_of_collision import TarTypeOfCollision
from .TAR.location_of_first_contact import TarLocationOfFirstContact
from .TAR.primary_collision_occurrence import TarPrimaryCollisionOccurrence
from .TAR.pedestrian_location import TarPedestrianLocation
from .TAR.pedestrian_action import TarPedestrianAction
from .TAR.entity_type import TarEntityType
from .TAR.contributing_factors import TarContributingFactors
from .TAR.damage_location import TarDamageLocation
from .TAR.damage_severity import TarDamageSeverity
from .TAR.pre_collision_action import TarPreCollisionAction
from .TAR.vehicle_type import TarVehicleType
from .TAR.vehicle_use import TarVehicleUse
from .TAR.position import TarPosition
from .TAR.safety_equipment import TarSafetyEquipment
from .TAR.ejection import TarEjection
from .TAR.injury_location import TarInjuryLocation
from .TAR.injury_type import TarInjuryType
from .TAR.victim_status import TarVictimStatus
from .TAR.taken_to import TarTakenTo
from .TAR.taken_by import TarTakenBy
from .TAR.injury_classification import TarInjuryClassification
from .TAR.police_district import TarPoliceDistrict
from .TAR.police_agency import TarPoliceAgency
