apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: for migate pod
    openshift.io/display-name: for migate pod
    openshift.io/long-description: This template deploys pod migrate
    tags: df-db-migrate
  name: df-db-migrate-pod-template
labels:
  app.kubernetes.io/component: df-db-migrate-pod
  app.kubernetes.io/name: df
  app.kubernetes.io/managed-by: template
objects:
  # - apiVersion: v1
  #   kind: Pod
  #   metadata:
  #     labels:
  #       app: migrate-pod
  #     name: migrate-pod
  #   spec:
  #     imagePullSecrets:
  #       - name: artifactory-pull-secret
  #     containers:
  #     - image: ${IMAGE_NAME}
  #       name: migrate-pod
  #       env:
  #       - name: DB_HOST
  #         value: ${DB_HOST}
  #       - name: DB_PORT
  #         value: ${DB_PORT}
  #       - name: DB_NAME
  #         value: ${DB_NAME}
  #       - name: DB_USER
  #         value: ${DB_USER}
  #       - name: DB_PASS
  #         value: ${DB_PASS}
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: db-migrate-job
    spec:
      completions: 1
      template:
        spec:
          imagePullSecrets:
            - name: artifactory-pull-secret
          containers:
          - image: ${IMAGE_NAME}
            name: migrate-pod
            env:
            - name: DB_HOST
              value: ${DB_HOST}
            - name: DB_PORT
              value: ${DB_PORT}
            - name: DB_NAME
              value: ${DB_NAME}
            - name: DB_USER
              value: ${DB_USER}
            - name: DB_PASS
              value: ${DB_PASS}
          restartPolicy: Never
      backoffLimit: 1

parameters:
  - name: IMAGE_NAME
  - name: DB_HOST
  - name: DB_PORT
  - name: DB_NAME
  - name: DB_USER
  - name: DB_PASS
