FROM python:3.12-alpine

COPY all_mock_svc/requirements.txt /tmp/

RUN pip install -U pip setuptools wheel && \
    sha256sum /tmp/requirements.txt > /tmp/requirements.sha256  && \
    cd /tmp && pip install -r requirements.txt


COPY all_mock_svc /tmp/mock_services/all_mock_svc
WORKDIR /tmp/mock_services/all_mock_svc

# CMD [ "gunicorn", "--bind", "0.0.0.0:5000", "--pythonpath", "/tmp/mock_services/icbc_mock_svc", "wsgi" ]
CMD [ "gunicorn", "--bind", "0.0.0.0:5000",  "wsgi" ]