FROM artifacts.developer.gov.bc.ca/dbe7-images/rhel8-python39:1-196.1725368453

COPY prohibition_web_svc/requirements.txt /tmp/

RUN pip3 install -U pip
RUN pip3 install -r /tmp/requirements.txt

# RUN useradd --create-home appuser
# WORKDIR /home/appuser
# USER appuser

COPY common /home/appuser/python/common
COPY prohibition_web_svc /home/appuser/python/prohibition_web_svc

ENV PYTHONPATH /home/appuser/

# RUN ["python", "-m", "pytest"]
CMD [ "gunicorn", "--bind", "0.0.0.0:5000", "--pythonpath", "/home/appuser/python/prohibition_web_svc", "app:create_app()" ]