FROM artifacts.developer.gov.bc.ca/dbe7-images/rhel8-python38:1-127.1684740820
ARG VERSION
ENV VERSION=$VERSION

ARG DB_HOST
ENV DB_HOST=$DB_HOST

ARG DB_NAME
ENV DB_NAME=$DB_NAME

ARG DB_PASS
ENV DB_PASS=$DB_PASS

ARG DB_PORT
ENV DB_PORT=$DB_PORT

ARG DB_USER
ENV DB_USER=$DB_USER

COPY prohibition_web_svc/requirements.txt ${APP_ROOT}/src/

RUN pip install --upgrade pip
RUN source /opt/app-root/etc/scl_enable && \
    set -x && \
    pip3 install -U pip setuptools wheel && \
    sha256sum "${APP_ROOT}/src/requirements.txt" > ${APP_ROOT}/requirements.sha256  && \
    cd ${APP_ROOT}/src && pip3 install -r requirements.txt

COPY __init__.py ${APP_ROOT}/src/python/
COPY common ${APP_ROOT}/src/python/common
COPY prohibition_web_svc ${APP_ROOT}/src/python/prohibition_web_svc

# RUN ["python", "-m", "pytest", "python/prohibition_web_svc"]

CMD [ "gunicorn", "--error-logfile", "-", "--bind", "0.0.0.0:5000", "--pythonpath", "python/prohibition_web_svc", "app:create_app()" ]