name: ci-workflow

on:
  workflow_call:
    inputs:
      DOCKER_CONTEXT:
        required: true
        type: string
      DOCKER_FILE:
        required: true
        type: string
      DOCKER_IMAGE_NAME:
        # required: true
        type: string
      # OPENSHIFT_SERVER_URL_SILVER:
      #   required: true
      #   type: string
      # OPENSHIFT_SA_PIPELINE_TOKEN_SILVER:
      #   required: true
      #   type: string
      # OPENSHIFT_LICENSE_PLATE_SILVER:
      #   required: true
      #   type: string
    secrets:
      DOCKER_REGISTRY:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.DOCKER_CONTEXT }}
          file: ${{ inputs.DOCKER_FILE }}
          push: false
          load: true
          tags:  ${{ inputs.DOCKER_IMAGE_NAME }}:latest
      - name: Check Images
        run: |
          docker images
      - name: Run Trivy vulnerability scanner - stdout
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          scan-type: image
          image-ref: ${{ inputs.DOCKER_IMAGE_NAME }}:latest
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: HIGH,CRITICAL
      - name: Run Trivy vulnerability scanner- save to file
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        if: always()
        with:
          scan-type: image
          image-ref: ${{ inputs.DOCKER_IMAGE_NAME }}:latest
          format: 'template'
          # exit-code: '1'
          ignore-unfixed: true
          template: "@trivy/github-markdown.tpl"
          output: trivy.md
          severity: HIGH,CRITICAL   
      - name: Send results to Status
        if: always()
        run: |
          cat trivy.md >> $GITHUB_STEP_SUMMARY   
      # - uses: mshick/add-pr-comment@v2
      #   if: always()
      #   with:
      #     message-path: |
      #       trivy-results.sarif
      

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.DOCKER_CONTEXT }}
          file: ${{ inputs.DOCKER_FILE }}
          push: false
