import { useRecoilValue } from "recoil";
import { userAtom } from "../../atoms/users";

export const InitialValues = () => {
  const user = useRecoilValue(userAtom);

  return {
    //common fields
    IRP: false,
    VI: false,
    TwentyFourHour: false,
    TwelveHour: false,
    confirmation_of_service_date: null,
    drivers_licence_jurisdiction: { value: "BC", label: "BRITISH COLUMBIA" },
    driver_licence_no: "",
    driver_last_name: "",
    driver_given_name: "",
    driver_dob: "",
    driver_address: "",
    driver_city: "",
    driver_phone: "",
    driver_prov_state: { value: "BC", label: "BRITISH COLUMBIA" },
    driver_postal: "",
    vehicle_jurisdiction: { value: "BC", label: "BRITISH COLUMBIA" },
    vehicle_plate_no: "",
    vehicle_registration_no: "",
    vehicle_year: "",
    vehicle_mk_md: "",
    vehicle_style: "",
    vehicle_colour: [],
    nsc_prov_state: { value: "BC", label: "BRITISH COLUMBIA" },
    vehicle_vin_no: "",
    nsc_no: "",
    owned_by_corp: false,
    corporation_name: "",
    regist_owner_last_name: "",
    regist_owner_first_name: "",
    regist_owner_address: "",
    regist_owner_dob: "",
    regist_owner_city: "",
    regist_owner_prov_state: {},
    regist_owner_postal: "",
    "officer-lastname": user.last_name || "",
    "officer-prime-id": user.badge_number || "",
    "officer-agency": user.agency || "",
    //24-hour form fields
    vehicle_impounded: "",
    location_of_keys: "",
    reason_for_not_impounding: "",
    "ILO-options": {},
    "ILO-name": "",
    "ILO-address": "",
    "ILO-city": "",
    "ILO-phone": "",
    vehicle_released_to: "",
    date_released: "",
    time_released: "",
    type_of_prohibition: "",
    intersection_or_address_of_offence: "",
    offence_city: {},
    agency_file_no: "",
    date_of_driving: "",
    time_of_driving: "",
    witnessed_by_officer: false,
    admission_by_driver: false,
    independent_witness: false,
    reasonable_ground_other: false,
    prescribed_test_used: "",
    test_used_alcohol: "",
    asd_expiry_date: "",
    result_alcohol: "",
    bac_result_mg: "",
    test_used_drugs: "",
    THC: false,
    Cocaine: false,
    "document-served": "",
    confirmation_of_service: false,
    gender: "",
    driver_licence_expiry: "",
    driver_licence_class: "",
    unlicenced_prohibition_number: "",
    belief_driver_bc_resident: "",
    out_of_province_dl: "",
    out_of_province_dl_number: "",
    date_of_impound: "",
    irp_impound: "",
    irp_impound_duration: "",
    IRP_number: "",
    VI_number: "22-1312342",
    excessive_speed: false,
    prohibited: false,
    suspended: false,
    street_racing: false,
    stunt_driving: false,
    motorcycle_seating: false,
    motorcycle_restrictions: false,
    unlicensed: false,
    linkage_location_of_keys: false,
    linkage_location_of_keys_explanation: "",
    linkage_driver_principal: false,
    linkage_owner_in_vehicle: false,
    linkage_owner_aware_possesion: false,
    linkage_vehicle_transfer_notice: false,
    linkage_other: false,
    speed_limit: "",
    vehicle_speed: "",
    speed_estimation_technique: "",
    speed_confirmation_technique: "",
    incident_details: "",
    incident_details_extra_page: false,
    is_nsc: false,
  };
};
