import { useRecoilValue } from 'recoil';
import { userAtom } from '../../atoms/users';

export const InitialValues = () => {
    const user = useRecoilValue(userAtom);

    return {
        //common fields
        "IRP": false,
        "VI": false,
        "24Hour": false,
        "12Hour": false,
        "drivers_licence_jurisdiction":{ value: 'BC', label: 'BRITISH COLUMBIA' },
        "drivers_licence_no":'',
        "driver_last_name":'',
        "driver_given_name":'',
        "driver_dob": '',
        "driver_address":'',
        "driver_city":'',
        "driver_phone": '',
        "driver_prov_state":{ value: 'BC', label: 'BRITISH COLUMBIA' },
        "driver_postal":'',
        "vehicle_jurisdiction":{ value: 'BC', label: 'BRITISH COLUMBIA' },
        "vehicle_plate_no": '',
        "vehicle_registration_no": '',
        "vehicle_year": '',
        "vehicle_mk_md": '',
        "vehicle_style": '',
        "vehicle_colour": [],
        "nsc_prov_state":{ value: 'BC', label: 'BRITISH COLUMBIA' },
        "vehicle_vin_no": '',
        "nsc_no": '',
        "owned_by_corp" : false,
        "corporation_name": '',
        "regist_owner_last_name":'',
        "regist_owner_first_name": '',
        "regist_owner_address": '',
        "regist_owner_dob": '',
        "regist_owner_city": '',
        "regist_owner_prov_state": {},
        "regist_owner_postal": '',
        "officer-lastname":user.last_name || '',
        "officer-prime-id":user.badge_number || '',
        "officer-agency":user.agency || '',
        //24-hour form fields
        "vehicle_impounded":'',
        "location_of_keys": '',
        "reason_for_not_impounding": '',
        'ILO-options': '',
        "ILO-name": '',
        "ILO-address":'',
        "ILO-city":'',
        "ILO-phone":'',
        "vehicle_released_to": '',
        "date_released": '',
        "time_released": '',
        "type_of_prohibition": '',
        "intersection_or_address_of_offence":'',
        "offence_city":'',
        "agency_file_no":'',
        "date_of_driving":'',
        "time_of_driving": '',
        "witnessed-by-officer":false,
        "admission-by-driver":false,
        "independent-witness":false,
        "video-surveillance":false,
        "reasonable_ground_other":false,
        "prescribed_test_used":'',
        "test_used_alcohol": '',
        "asd_expiry_date": '',
        "result_alcohol": '',
        "bac_result_mg": '',
        "test_used_drugs": '',
        "THC":false,
        "Cocaine":false,
        "document-served":'',
        "certify-notice-delivery":false
    }
}