# FROM python:3.9-slim
FROM rhel8-python39:1-196.1725368453
ARG VERSION
ENV VERSION=$VERSION

COPY task_scheduler/requirements.txt /tmp/

RUN pip install --upgrade pip
RUN pip install -r /tmp/requirements.txt

WORKDIR /app
ENV PYTHONPATH /app/

COPY common /app/python/common
COPY task_scheduler /app/python/task_scheduler
COPY prohibition_web_svc/models.py /app/python/task_scheduler/models.py

CMD [ "gunicorn", "--error-logfile", "-", "--bind", "0.0.0.0:5000", "--pythonpath", "/app/python/task_scheduler", "main:create_app()" ]