FROM python:3.9-slim
ARG VERSION
ENV VERSION=$VERSION

COPY task_scheduler/requirements.txt /tmp/

RUN pip install --upgrade pip
RUN pip install -r /tmp/requirements.txt

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

ENV PYTHONPATH /home/appuser/

COPY common /home/appuser/python/common
COPY task_scheduler /home/appuser/python/task_scheduler

CMD [ "gunicorn", "--error-logfile", "-", "--bind", "0.0.0.0:5000", "--pythonpath", "/home/appuser/python/task_scheduler", "main:create_app()" ]