name: roadside_forms_frontend-cd

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master
      - main
    paths:
      - roadside-forms-frontend/frontend_web_app/**
      - .github/workflows/roadside_forms_frontend-cd.yml
      - trigger.txt

jobs:
  run_automated_tests:
    uses: ./.github/workflows/automated-testing-workflow.yml
    with:
      BUILD_CONTEXT: roadside-forms-frontend/frontend_web_app
      NODE_VERSION: 16.14.2
    secrets: inherit
  # CD:
  #   uses: ./.github/workflows/cd-workflow.yml
  #   needs: run_automated_tests
  #   with:
  #     DOCKER_CONTEXT: roadside-forms-frontend/frontend_web_app
  #     DOCKER_FILE: roadside-forms-frontend/frontend_web_app/Dockerfile
  #     DOCKER_IMAGE_NAME: rsbc-roadside-forms-frontend
  #   secrets: inherit
